#include "DependenciesHelper.h"

// const std::unordered_set<ParamId> DependenciesHelper::common_deps = {
//     ParamId{ParameterType::SM, "SMINPUTS", 1},
//     ParamId{ParameterType::SM, "SMINPUTS", 2},
//     ParamId{ParameterType::SM, "SMINPUTS", 3},
//     ParamId{ParameterType::SM, "SMINPUTS", 4},
//     ParamId{ParameterType::SM, "SMINPUTS", 5},
//     ParamId{ParameterType::SM, "SMINPUTS", 6},
//     ParamId{ParameterType::SM, "SMINPUTS", {7, 1}},
//     ParamId{ParameterType::SM, "SMINPUTS", {7, 2}},
//     ParamId{ParameterType::SM, "MASS", 1},
//     ParamId{ParameterType::SM, "MASS", 2},
//     ParamId{ParameterType::SM, "MASS", 3},
//     ParamId{ParameterType::SM, "MASS", 4},
//     ParamId{ParameterType::SM, "MASS", 11},
//     ParamId{ParameterType::SM, "MASS", 13},
//     ParamId{ParameterType::SM, "MASS", 15},
//     ParamId{ParameterType::SM, "MASS", 24},
//     ParamId{ParameterType::SM, "MASS", 25},
//     ParamId{ParameterType::SM, "VCKM", {0, 0}},
//     ParamId{ParameterType::SM, "VCKM", {0, 1}},
//     ParamId{ParameterType::SM, "VCKM", {0, 2}},
//     ParamId{ParameterType::SM, "VCKM", {1, 0}},
//     ParamId{ParameterType::SM, "VCKM", {1, 1}},
//     ParamId{ParameterType::SM, "VCKM", {1, 2}},
//     ParamId{ParameterType::SM, "VCKM", {2, 0}},
//     ParamId{ParameterType::SM, "VCKM", {2, 1}},
//     ParamId{ParameterType::SM, "VCKM", {2, 2}},
//     // ParamId{ParameterType::SM, "UPMNS", {0, 0}},
//     // ParamId{ParameterType::SM, "UPMNS", {0, 1}},
//     // ParamId{ParameterType::SM, "UPMNS", {0, 2}},
//     // ParamId{ParameterType::SM, "UPMNS", {1, 0}},
//     // ParamId{ParameterType::SM, "UPMNS", {1, 1}},
//     // ParamId{ParameterType::SM, "UPMNS", {1, 2}},
//     // ParamId{ParameterType::SM, "UPMNS", {2, 0}},
//     // ParamId{ParameterType::SM, "UPMNS", {2, 1}},
//     // ParamId{ParameterType::SM, "UPMNS", {2, 2}},
//     ParamId{ParameterType::WILSON, "EW_SCALE", 1},
//     ParamId{ParameterType::WILSON, "B_SCALE", 1},
//     // ParamId{ParameterType::WILSON, "D_SCALE", 1},
//     // ParamId{ParameterType::WILSON, "K_SCALE", 1},
// };

// const std::map<DecayId, std::unordered_set<ParamId>> DependenciesHelper::dep_lists = {
//     {DecayMapper::to_id(Decays::B__D_l_nu), {
//         ParamId{ParameterType::FLAVOR, "FMASS", 511},
//         ParamId{ParameterType::FLAVOR, "FMASS", 411},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 511},
//         ParamId{ParameterType::DECAY, "B_Dlnu", 1},
//         ParamId{ParameterType::DECAY, "B_Dlnu", 2},
//         ParamId{ParameterType::DECAY, "B_Dlnu", 3},
//     }},
//     {DecayMapper::to_id(Decays::B__Dstar_l_nu), {
//         ParamId{ParameterType::FLAVOR, "FMASS", 511},
//         ParamId{ParameterType::FLAVOR, "FMASS", 413},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 511},
//         ParamId{ParameterType::DECAY, "B_Dslnu", 1},
//         ParamId{ParameterType::DECAY, "B_Dslnu", 2},
//         ParamId{ParameterType::DECAY, "B_Dslnu", 3},
//         ParamId{ParameterType::DECAY, "B_Dslnu", 4},
//     }},
//     {DecayMapper::to_id(Decays::B__K_l_l), {
//         ParamId{ParameterType::FLAVOR, "FMASS", 511},
//         ParamId{ParameterType::FLAVOR, "FMASS", 521},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 511},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 521},
//         ParamId{ParameterType::FLAVOR, "FMASS", 311},
//         ParamId{ParameterType::FLAVOR, "FMASS", 321},
//         ParamId{ParameterType::FLAVOR, "FCONST", {311, 1}},
//         ParamId{ParameterType::FLAVOR, "FCONST", {321, 1}},
//         ParamId{ParameterType::DECAY, "B_K", {8, 1}},
//         ParamId{ParameterType::DECAY, "B_K", {8, 2}},
//         ParamId{ParameterType::DECAY, "B_K", 13},
//         ParamId{ParameterType::DECAY, "B_K", 14},
//         ParamId{ParameterType::DECAY, "B_K", 16},
//         ParamId{ParameterType::DECAY, "B_K", {18, 1, 1}},
//         ParamId{ParameterType::DECAY, "B_K", {18, 1, 2}},
//         ParamId{ParameterType::DECAY, "B_K", {18, 1, 3}},
//         ParamId{ParameterType::DECAY, "B_K", {18, 1, 4}},
//         ParamId{ParameterType::DECAY, "B_K", {18, 2, 1}},
//         ParamId{ParameterType::DECAY, "B_K", {18, 2, 2}},
//         ParamId{ParameterType::DECAY, "B_K", {18, 2, 3}},
//         ParamId{ParameterType::DECAY, "B_K", {18, 2, 4}},
//         ParamId{ParameterType::DECAY, "B_K", {18, 3, 1}},
//         ParamId{ParameterType::DECAY, "B_K", {18, 3, 2}},
//         ParamId{ParameterType::DECAY, "B_K", {18, 3, 3}},
//         ParamId{ParameterType::DECAY, "B_K", {18, 3, 4}},
//         // ParamId{ParameterType::DECAY, "B_K", {1, 1, 0}},
//         // ParamId{ParameterType::DECAY, "B_K", {1, 1, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {1, 1, 2}},
//         // ParamId{ParameterType::DECAY, "B_K", {1, 1, 3}},
//         // ParamId{ParameterType::DECAY, "B_K", {1, 2, 0}},
//         // ParamId{ParameterType::DECAY, "B_K", {1, 2, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {1, 2, 2}},
//         // ParamId{ParameterType::DECAY, "B_K", {1, 2, 3}},
//         // ParamId{ParameterType::DECAY, "B_K", {1, 3, 0}},
//         // ParamId{ParameterType::DECAY, "B_K", {1, 3, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {1, 3, 2}},
//         // ParamId{ParameterType::DECAY, "B_K", {1, 3, 3}},
//         // ParamId{ParameterType::DECAY, "B_K", {2, 1, 0}},
//         // ParamId{ParameterType::DECAY, "B_K", {2, 1, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {2, 1, 2}},
//         // ParamId{ParameterType::DECAY, "B_K", {2, 2, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {2, 2, 2}},
//         // ParamId{ParameterType::DECAY, "B_K", {2, 3, 0}},
//         // ParamId{ParameterType::DECAY, "B_K", {2, 3, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {2, 3, 2}},
//         ParamId{ParameterType::DECAY, "B_K", {3, 1, 0}},
//         ParamId{ParameterType::DECAY, "B_K", {3, 1, 1}},
//         ParamId{ParameterType::DECAY, "B_K", {3, 1, 2}},
//         ParamId{ParameterType::DECAY, "B_K", {3, 2, 1}},
//         ParamId{ParameterType::DECAY, "B_K", {3, 2, 2}},
//         ParamId{ParameterType::DECAY, "B_K", {3, 3, 0}},
//         ParamId{ParameterType::DECAY, "B_K", {3, 3, 1}},
//         ParamId{ParameterType::DECAY, "B_K", {3, 3, 2}},
//         // ParamId{ParameterType::DECAY, "B_K", {4, 1, 0}},
//         // ParamId{ParameterType::DECAY, "B_K", {4, 1, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {4, 1, 2}},
//         // ParamId{ParameterType::DECAY, "B_K", {4, 2, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {4, 2, 2}},
//         // ParamId{ParameterType::DECAY, "B_K", {4, 3, 0}},
//         // ParamId{ParameterType::DECAY, "B_K", {4, 3, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {4, 3, 2}},
//         // ParamId{ParameterType::DECAY, "B_K", {5, 1, 0}},
//         // ParamId{ParameterType::DECAY, "B_K", {5, 1, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {5, 1, 2}},
//         // ParamId{ParameterType::DECAY, "B_K", {5, 2, 0}},
//         // ParamId{ParameterType::DECAY, "B_K", {5, 2, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {5, 3, 0}},
//         // ParamId{ParameterType::DECAY, "B_K", {5, 3, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {5, 3, 2}},
//         // ParamId{ParameterType::DECAY, "B_K", {6, 1, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {6, 1, 2}},
//         // ParamId{ParameterType::DECAY, "B_K", {6, 2, 0}},
//         // ParamId{ParameterType::DECAY, "B_K", {6, 2, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {6, 2, 2}},
//         // ParamId{ParameterType::DECAY, "B_K", {6, 3, 0}},
//         // ParamId{ParameterType::DECAY, "B_K", {6, 3, 1}},
//         // ParamId{ParameterType::DECAY, "B_K", {6, 3, 2}},
//     }},
//     {DecayMapper::to_id(Decays::B__Kstar_l_l), {
//         // TODO : Missing FFs
//         ParamId{ParameterType::FLAVOR, "FMASS", 511},
//         ParamId{ParameterType::FLAVOR, "FMASS", 521},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 511},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 521},
//         ParamId{ParameterType::FLAVOR, "FMASS", 313},
//         ParamId{ParameterType::FLAVOR, "FMASS", 323},
//         ParamId{ParameterType::FLAVOR, "FCONST", {313, 1}},
//         ParamId{ParameterType::FLAVOR, "FCONST", {313, 2}},
//         ParamId{ParameterType::FLAVOR, "FCONST", {323, 1}},
//         ParamId{ParameterType::FLAVOR, "FCONST", {323, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {7, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {7, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {8, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {8, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", 9},
//         ParamId{ParameterType::DECAY, "B_Ks", 10},
//         ParamId{ParameterType::DECAY, "B_Ks", 11},
//         ParamId{ParameterType::DECAY, "B_Ks", {12, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {12, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", 14},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 1, 0}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 1, 1}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 1, 2}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 2, 0}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 2, 1}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 2, 2}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 3, 0}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 3, 1}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 3, 2}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 4, 0}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 4, 1}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 4, 2}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 5, 0}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 5, 1}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 5, 2}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 6, 0}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 6, 1}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 6, 2}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 7, 0}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 7, 1}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 7, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 1, 0}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 1, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 1, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 2, 0}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 2, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 2, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 3, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 3, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 4, 0}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 4, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 4, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 5, 0}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 5, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 5, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 6, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 6, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 7, 0}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 7, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 7, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 1, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 1, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 1, 3}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 1, 4}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 1, 5}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 1, 6}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 2, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 2, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 2, 3}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 2, 4}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 2, 5}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 2, 6}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 3}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 4}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 5}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 6}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 7}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 8}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 4, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 4, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 4, 3}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 4, 4}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 4, 5}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 4, 6}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 5, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 5, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 5, 3}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 5, 4}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 5, 5}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 5, 6}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 3}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 4}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 5}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 6}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 7}},
//         ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 8}},
//     }},
//     {DecayMapper::to_id(Decays::B__Kstar_gamma), {
//         ParamId{ParameterType::FLAVOR, "FMASS", 511},
//         ParamId{ParameterType::FLAVOR, "FMASS", 521},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 511},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 521},
//         ParamId{ParameterType::FLAVOR, "FMASS", 313},
//         ParamId{ParameterType::FLAVOR, "FMASS", 323},
//         ParamId{ParameterType::FLAVOR, "FCONST", {313, 1}},
//         ParamId{ParameterType::FLAVOR, "FCONST", {313, 2}},
//         ParamId{ParameterType::FLAVOR, "FCONST", {323, 1}},
//         ParamId{ParameterType::FLAVOR, "FCONST", {323, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", 13},
//         ParamId{ParameterType::DECAY, "B_Ks", 14},
//         ParamId{ParameterType::DECAY, "B_Ks", 17},
//         ParamId{ParameterType::DECAY, "B_Ks", {7, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {7, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {8, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {8, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", 9},
//         ParamId{ParameterType::DECAY, "B_Ks", 10},
//         ParamId{ParameterType::DECAY, "B_Ks", 11},
//         ParamId{ParameterType::DECAY, "B_Ks", {12, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {12, 2}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 1, 0}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 1, 1}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 1, 2}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 2, 0}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 2, 1}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 2, 2}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 3, 0}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 3, 1}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 3, 2}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 4, 0}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 4, 1}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 4, 2}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 5, 0}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 5, 1}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 5, 2}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 6, 0}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 6, 1}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 6, 2}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 7, 0}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 7, 1}},
//         // ParamId{ParameterType::DECAY, "B_Ks", {1, 7, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 1, 0}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 1, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 1, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 2, 0}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 2, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 2, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 3, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 3, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 4, 0}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 4, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 4, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 5, 0}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 5, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 5, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 6, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 6, 2}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 7, 0}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 7, 1}},
//         ParamId{ParameterType::DECAY, "B_Ks", {3, 7, 2}},
//     }},
//     {DecayMapper::to_id(Decays::B__l_l), {
//         ParamId{ParameterType::FLAVOR, "FMASS", 531},
//         ParamId{ParameterType::FLAVOR, "FMASS", 511},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 531},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 511},
//         ParamId{ParameterType::FLAVOR, "FCONST", {511, 1}},
//         ParamId{ParameterType::FLAVOR, "FCONST", {531, 1}},
//         ParamId{ParameterType::DECAY, "B_ll", 1},
//         ParamId{ParameterType::DECAY, "B_ll", 2},
//     }},
//     {DecayMapper::to_id(Decays::B__l_nu), {
//         ParamId{ParameterType::FLAVOR, "FMASS", 521},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 521},
//         ParamId{ParameterType::FLAVOR, "FCONST", {521, 1}}
//     }},
//     {DecayMapper::to_id(Decays::Bs__phi_l_l), {
//         ParamId{ParameterType::FLAVOR, "FMASS", 531},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 531},
//         ParamId{ParameterType::FLAVOR, "FMASS", 333},
//         ParamId{ParameterType::FLAVOR, "FCONST", {333, 1}},
//         ParamId{ParameterType::FLAVOR, "FCONST", {333, 2}},
//         ParamId{ParameterType::DECAY, "B_ll", 1},
//         ParamId{ParameterType::DECAY, "B_phi", {7, 1}},
//         ParamId{ParameterType::DECAY, "B_phi", {7, 2}},
//         ParamId{ParameterType::DECAY, "B_phi", {8, 1}},
//         ParamId{ParameterType::DECAY, "B_phi", {8, 2}},
//         ParamId{ParameterType::DECAY, "B_phi", 9},
//         ParamId{ParameterType::DECAY, "B_phi", 10},
//         ParamId{ParameterType::DECAY, "B_phi", 11},
//         ParamId{ParameterType::DECAY, "B_phi", {12, 1}},
//         ParamId{ParameterType::DECAY, "B_phi", {12, 2}},
//         ParamId{ParameterType::DECAY, "B_phi", 14},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 1, 0}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 1, 1}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 1, 2}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 2, 0}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 2, 1}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 2, 2}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 3, 0}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 3, 1}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 3, 2}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 4, 0}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 4, 1}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 4, 2}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 5, 0}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 5, 1}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 5, 2}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 6, 0}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 6, 1}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 6, 2}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 7, 0}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 7, 1}},
//         // ParamId{ParameterType::DECAY, "B_phi", {1, 7, 2}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 1, 0}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 1, 1}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 1, 2}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 2, 0}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 2, 1}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 2, 2}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 3, 1}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 3, 2}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 4, 0}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 4, 1}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 4, 2}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 5, 0}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 5, 1}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 5, 2}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 6, 1}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 6, 2}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 7, 0}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 7, 1}},
//         ParamId{ParameterType::DECAY, "B_phi", {3, 7, 2}},
//     }},
//     {DecayMapper::to_id(Decays::B__Xs_gamma), {
//         ParamId{ParameterType::DECAY, "B_Xs", 2},
//         ParamId{ParameterType::DECAY, "B_Xs", 3},
//         ParamId{ParameterType::DECAY, "B_Xs", 4},
//         ParamId{ParameterType::DECAY, "B_Xs", 5},
//         ParamId{ParameterType::DECAY, "B_Xs", 6},
//         ParamId{ParameterType::DECAY, "B_Xs", 7},
//         ParamId{ParameterType::DECAY, "B_Xs", 10},
//     }},
//     {DecayMapper::to_id(Decays::B__Xs_l_l), {
//         ParamId{ParameterType::FLAVOR, "FMASS", 421},
//         ParamId{ParameterType::DECAY, "B_Xs", 2},
//         ParamId{ParameterType::DECAY, "B_Xs", 6},
//         ParamId{ParameterType::DECAY, "B_Xsll", 1},
//         ParamId{ParameterType::DECAY, "B_Xsll", 2},
//         ParamId{ParameterType::DECAY, "B_Xsll", {3, 11, 0}},
//         ParamId{ParameterType::DECAY, "B_Xsll", {3, 11, 1}},
//         ParamId{ParameterType::DECAY, "B_Xsll", {3, 11, 2}},
//         ParamId{ParameterType::DECAY, "B_Xsll", {3, 13, 0}},
//         ParamId{ParameterType::DECAY, "B_Xsll", {3, 13, 1}},
//         ParamId{ParameterType::DECAY, "B_Xsll", {3, 13, 2}},
//     }},
//     {DecayMapper::to_id(Decays::D__l_nu), {
//         ParamId{ParameterType::FLAVOR, "FMASS", 411},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 411},
//         ParamId{ParameterType::FLAVOR, "FCONST", {411, 1}}
//     }},
//     {DecayMapper::to_id(Decays::Ds__l_nu), {
//         ParamId{ParameterType::FLAVOR, "FMASS", 431},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 431},
//         ParamId{ParameterType::FLAVOR, "FCONST", {431, 1}}
//     }},
//     {DecayMapper::to_id(Decays::K__l_l), {
//         ParamId{ParameterType::FLAVOR, "FMASS", 111},
//         ParamId{ParameterType::FLAVOR, "FMASS", 113},
//         ParamId{ParameterType::FLAVOR, "FMASS", 311},
//         ParamId{ParameterType::FLAVOR, "FCONST", {311, 1}},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 130},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 310},
//         ParamId{ParameterType::DECAY, "K_ll", 1},
//         ParamId{ParameterType::DECAY, "K_ll", 2},
//         ParamId{ParameterType::DECAY, "K_ll", 3},
//         ParamId{ParameterType::DECAY, "K_ll", 4},
//     }},
//     {DecayMapper::to_id(Decays::K__l_nu), {
//         ParamId{ParameterType::DECAY, "K_lnu", 1},
//         ParamId{ParameterType::FLAVOR, "FMASS", 321},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 321},
//         ParamId{ParameterType::FLAVOR, "FCONST", {321, 1}},
//         ParamId{ParameterType::FLAVOR, "FMASS", 211},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 211},
//         ParamId{ParameterType::FLAVOR, "FCONST", {211, 1}},
//         ParamId{ParameterType::FLAVOR, "FCONSTRATIO", {321, 211, 1, 1}}
//     }},
//     {DecayMapper::to_id(Decays::K__pi_nu_nu), {
//         ParamId{ParameterType::DECAY, "K_pi", 1},
//         ParamId{ParameterType::DECAY, "K_pi", 2},
//         ParamId{ParameterType::DECAY, "K_pi", 3},
//     }},
//     {DecayMapper::to_id(Decays::Lambda_b__Lambda_l_l), {
//         ParamId{ParameterType::FLAVOR, "FMASS", 321},
//         ParamId{ParameterType::FLAVOR, "FMASS", 521},
//         ParamId{ParameterType::FLAVOR, "FMASS", 5122},
//         ParamId{ParameterType::FLAVOR, "FMASS", 3122},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 5122},
//         ParamId{ParameterType::DECAY, "Lb_L", 8},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 1, 0}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 1, 1}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 1, 2}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 2, 0}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 2, 1}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 2, 2}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 3, 0}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 3, 1}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 3, 2}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 4, 0}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 4, 1}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 4, 2}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 5, 0}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 5, 1}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 5, 2}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 6, 0}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 6, 1}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 6, 2}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 7, 0}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 7, 1}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 7, 2}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 8, 0}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 8, 1}},
//         ParamId{ParameterType::DECAY, "Lb_L", {1, 8, 2}},
//     }},
//     {DecayMapper::to_id(Decays::M0_Mix), {
//         ParamId{ParameterType::FLAVOR, "FMASS", 311},
//         ParamId{ParameterType::FLAVOR, "FMASS", 421},
//         ParamId{ParameterType::FLAVOR, "FMASS", 511},
//         ParamId{ParameterType::FLAVOR, "FMASS", 531},
//         ParamId{ParameterType::FLAVOR, "FLIFE", 421},
//         ParamId{ParameterType::DECAY, "M0_Mix", 1},
//         ParamId{ParameterType::DECAY, "M0_Mix", 2},
//         ParamId{ParameterType::DECAY, "M0_Mix", 3},
//         ParamId{ParameterType::DECAY, "M0_Mix", {4, 1}},
//         ParamId{ParameterType::DECAY, "M0_Mix", {4, 2}},
//         ParamId{ParameterType::DECAY, "M0_Mix", {4, 3}},
//         ParamId{ParameterType::DECAY, "M0_Mix", {4, 4}},
//         ParamId{ParameterType::DECAY, "M0_Mix", {4, 5}},
//         ParamId{ParameterType::DECAY, "M0_Mix", 6},
//         ParamId{ParameterType::DECAY, "M0_Mix", 7},
//         ParamId{ParameterType::DECAY, "M0_Mix", 11},
//         ParamId{ParameterType::DECAY, "M0_Mix", 12},
//     }}
// };

// std::unordered_set<ParamId> DependenciesHelper::get_allowed_parameters(Observables id) {
//     ObservableId obs_id = ObservableMapper::to_id(id);

//     return get_allowed_parameters(obs_id);
// }

// bool DependenciesHelper::is_param_allowed(Observables id, ParamId pid) {
//     ObservableId obs_id = ObservableMapper::to_id(id);

//     return is_param_allowed(obs_id, pid);
// }

// std::unordered_set<ParamId> DependenciesHelper::get_allowed_parameters(ObservableId id) {
//     std::optional<DecayId> did = DecayMapper::get_decay_id(id);
//     if (!did.has_value()) {
//         LOG_WARN("No decay found for obs", id.str());
//         return {};
//     }

//     if (did.has_value()) {
//         auto decay_deps = dep_lists.at(did.value());
//         decay_deps.insert(common_deps.begin(), common_deps.end());
//         return decay_deps;
//     } else {
//         LOG_ERROR("ValueError", "Observable", ObservableMapper::str(id), "doesn't belong to any declared decay.");
//     }
// }

// bool DependenciesHelper::is_param_allowed(ObservableId id, ParamId pid) {
//     auto allowed = get_allowed_parameters(id);
//     return std::find(allowed.begin(), allowed.end(), pid) != allowed.end() 
//             && std::find(common_deps.begin(), common_deps.end(), pid) != common_deps.end();
// }

#include "DependenciesHelper.h"

const std::unordered_set<ParamId> DependenciesHelper::common_deps = {
    ParamId{ParameterType::SM, "SMINPUTS", 1},
    ParamId{ParameterType::SM, "SMINPUTS", 2},
    ParamId{ParameterType::SM, "SMINPUTS", 3},
    ParamId{ParameterType::SM, "SMINPUTS", 4},
    ParamId{ParameterType::SM, "SMINPUTS", 5},
    ParamId{ParameterType::SM, "SMINPUTS", 6},
    ParamId{ParameterType::SM, "SMINPUTS", {7, 1}},
    ParamId{ParameterType::SM, "SMINPUTS", {7, 2}},
    ParamId{ParameterType::SM, "EW", {1, 2}},
    ParamId{ParameterType::SM, "QCD", {5, 1}},
    ParamId{ParameterType::SM, "QCD", {5, 2}},
    ParamId{ParameterType::SM, "QCD", {5, 3}},
    ParamId{ParameterType::SM, "MASS", 1},
    ParamId{ParameterType::SM, "MASS", 2},
    ParamId{ParameterType::SM, "MASS", 3},
    ParamId{ParameterType::SM, "MASS", 4},
    ParamId{ParameterType::SM, "MASS", 11},
    ParamId{ParameterType::SM, "MASS", 13},
    ParamId{ParameterType::SM, "MASS", 15},
    ParamId{ParameterType::SM, "MASS", 24},
    ParamId{ParameterType::SM, "MASS", 25},
    ParamId{ParameterType::SM, "VCKM", {0, 0}},
    ParamId{ParameterType::SM, "VCKM", {0, 1}},
    ParamId{ParameterType::SM, "VCKM", {0, 2}},
    ParamId{ParameterType::SM, "VCKM", {1, 0}},
    ParamId{ParameterType::SM, "VCKM", {1, 1}},
    ParamId{ParameterType::SM, "VCKM", {1, 2}},
    ParamId{ParameterType::SM, "VCKM", {2, 0}},
    ParamId{ParameterType::SM, "VCKM", {2, 1}},
    ParamId{ParameterType::SM, "VCKM", {2, 2}},
    // ParamId{ParameterType::SM, "UPMNS", {0, 0}},
    // ParamId{ParameterType::SM, "UPMNS", {0, 1}},
    // ParamId{ParameterType::SM, "UPMNS", {0, 2}},
    // ParamId{ParameterType::SM, "UPMNS", {1, 0}},
    // ParamId{ParameterType::SM, "UPMNS", {1, 1}},
    // ParamId{ParameterType::SM, "UPMNS", {1, 2}},
    // ParamId{ParameterType::SM, "UPMNS", {2, 0}},
    // ParamId{ParameterType::SM, "UPMNS", {2, 1}},
    // ParamId{ParameterType::SM, "UPMNS", {2, 2}},
    ParamId{ParameterType::WILSON, "EW_SCALE", 1},
    ParamId{ParameterType::WILSON, "B_SCALE", 1},
    // ParamId{ParameterType::WILSON, "D_SCALE", 1},
    // ParamId{ParameterType::WILSON, "K_SCALE", 1},
};

const std::map<DecayId, std::unordered_set<ParamId>> DependenciesHelper::dep_lists = {
    {DecayMapper::to_id(Decays::B__D_l_nu), {
        ParamId{ParameterType::FLAVOR, "FMASS", 511},
        ParamId{ParameterType::FLAVOR, "FMASS", 411},
        ParamId{ParameterType::FLAVOR, "FLIFE", 511},
        ParamId{ParameterType::DECAY, "B_Dlnu", 1},
        ParamId{ParameterType::DECAY, "B_Dlnu", 2},
        ParamId{ParameterType::DECAY, "B_Dlnu", 3},
    }},
    {DecayMapper::to_id(Decays::B__Dstar_l_nu), {
        ParamId{ParameterType::FLAVOR, "FMASS", 511},
        ParamId{ParameterType::FLAVOR, "FMASS", 413},
        ParamId{ParameterType::FLAVOR, "FLIFE", 511},
        ParamId{ParameterType::DECAY, "B_Dslnu", 1},
        ParamId{ParameterType::DECAY, "B_Dslnu", 2},
        ParamId{ParameterType::DECAY, "B_Dslnu", 3},
        ParamId{ParameterType::DECAY, "B_Dslnu", 4},
    }},
    {DecayMapper::to_id(Decays::B__K_l_l), {
        ParamId{ParameterType::FLAVOR, "FMASS", 511},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FLIFE", 511},
        ParamId{ParameterType::FLAVOR, "FLIFE", 521},
        ParamId{ParameterType::FLAVOR, "FMASS", 311},
        ParamId{ParameterType::FLAVOR, "FMASS", 321},
        ParamId{ParameterType::FLAVOR, "FCONST", {311, 1}},
        ParamId{ParameterType::FLAVOR, "FCONST", {321, 1}},
        ParamId{ParameterType::DECAY, "B_K", {8, 1}},
        ParamId{ParameterType::DECAY, "B_K", {8, 2}},
        ParamId{ParameterType::DECAY, "B_K", 13},
        ParamId{ParameterType::DECAY, "B_K", 14},
        ParamId{ParameterType::DECAY, "B_K", {15, 1}},
        ParamId{ParameterType::DECAY, "B_K", {15, 2}},
        ParamId{ParameterType::DECAY, "B_K", 16},
        ParamId{ParameterType::DECAY, "B_K", {18, 1, 1}},
        ParamId{ParameterType::DECAY, "B_K", {18, 1, 2}},
        ParamId{ParameterType::DECAY, "B_K", {18, 1, 3}},
        ParamId{ParameterType::DECAY, "B_K", {18, 1, 4}},
        ParamId{ParameterType::DECAY, "B_K", {18, 2, 1}},
        ParamId{ParameterType::DECAY, "B_K", {18, 2, 2}},
        ParamId{ParameterType::DECAY, "B_K", {18, 2, 3}},
        ParamId{ParameterType::DECAY, "B_K", {18, 2, 4}},
        ParamId{ParameterType::DECAY, "B_K", {18, 3, 1}},
        ParamId{ParameterType::DECAY, "B_K", {18, 3, 2}},
        ParamId{ParameterType::DECAY, "B_K", {18, 3, 3}},
        ParamId{ParameterType::DECAY, "B_K", {18, 3, 4}},
        // ParamId{ParameterType::DECAY, "B_K", {1, 1, 0}},
        // ParamId{ParameterType::DECAY, "B_K", {1, 1, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {1, 1, 2}},
        // ParamId{ParameterType::DECAY, "B_K", {1, 1, 3}},
        // ParamId{ParameterType::DECAY, "B_K", {1, 2, 0}},
        // ParamId{ParameterType::DECAY, "B_K", {1, 2, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {1, 2, 2}},
        // ParamId{ParameterType::DECAY, "B_K", {1, 2, 3}},
        // ParamId{ParameterType::DECAY, "B_K", {1, 3, 0}},
        // ParamId{ParameterType::DECAY, "B_K", {1, 3, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {1, 3, 2}},
        // ParamId{ParameterType::DECAY, "B_K", {1, 3, 3}},
        // ParamId{ParameterType::DECAY, "B_K", {2, 1, 0}},
        // ParamId{ParameterType::DECAY, "B_K", {2, 1, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {2, 1, 2}},
        // ParamId{ParameterType::DECAY, "B_K", {2, 2, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {2, 2, 2}},
        // ParamId{ParameterType::DECAY, "B_K", {2, 3, 0}},
        // ParamId{ParameterType::DECAY, "B_K", {2, 3, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {2, 3, 2}},
        ParamId{ParameterType::DECAY, "B_K", {3, 1, 0}},
        ParamId{ParameterType::DECAY, "B_K", {3, 1, 1}},
        ParamId{ParameterType::DECAY, "B_K", {3, 1, 2}},
        ParamId{ParameterType::DECAY, "B_K", {3, 2, 1}},
        ParamId{ParameterType::DECAY, "B_K", {3, 2, 2}},
        ParamId{ParameterType::DECAY, "B_K", {3, 3, 0}},
        ParamId{ParameterType::DECAY, "B_K", {3, 3, 1}},
        ParamId{ParameterType::DECAY, "B_K", {3, 3, 2}},
        // ParamId{ParameterType::DECAY, "B_K", {4, 1, 0}},
        // ParamId{ParameterType::DECAY, "B_K", {4, 1, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {4, 1, 2}},
        // ParamId{ParameterType::DECAY, "B_K", {4, 2, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {4, 2, 2}},
        // ParamId{ParameterType::DECAY, "B_K", {4, 3, 0}},
        // ParamId{ParameterType::DECAY, "B_K", {4, 3, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {4, 3, 2}},
        // ParamId{ParameterType::DECAY, "B_K", {5, 1, 0}},
        // ParamId{ParameterType::DECAY, "B_K", {5, 1, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {5, 1, 2}},
        // ParamId{ParameterType::DECAY, "B_K", {5, 2, 0}},
        // ParamId{ParameterType::DECAY, "B_K", {5, 2, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {5, 3, 0}},
        // ParamId{ParameterType::DECAY, "B_K", {5, 3, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {5, 3, 2}},
        // ParamId{ParameterType::DECAY, "B_K", {6, 1, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {6, 1, 2}},
        // ParamId{ParameterType::DECAY, "B_K", {6, 2, 0}},
        // ParamId{ParameterType::DECAY, "B_K", {6, 2, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {6, 2, 2}},
        // ParamId{ParameterType::DECAY, "B_K", {6, 3, 0}},
        // ParamId{ParameterType::DECAY, "B_K", {6, 3, 1}},
        // ParamId{ParameterType::DECAY, "B_K", {6, 3, 2}},
    }},
    {DecayMapper::to_id(Decays::B__Kstar_l_l), {
        // TODO : Missing FFs
        ParamId{ParameterType::FLAVOR, "FMASS", 511},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FLIFE", 511},
        ParamId{ParameterType::FLAVOR, "FLIFE", 521},
        ParamId{ParameterType::FLAVOR, "FMASS", 313},
        ParamId{ParameterType::FLAVOR, "FMASS", 323},
        ParamId{ParameterType::FLAVOR, "FMASS", 421},
        ParamId{ParameterType::FLAVOR, "FMASS", 443},
        ParamId{ParameterType::FLAVOR, "FMASS", 100443},
        ParamId{ParameterType::FLAVOR, "FCONST", {313, 1}},
        ParamId{ParameterType::FLAVOR, "FCONST", {313, 2}},
        ParamId{ParameterType::FLAVOR, "FCONST", {323, 1}},
        ParamId{ParameterType::FLAVOR, "FCONST", {323, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {7, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {7, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {8, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {8, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", 9},
        ParamId{ParameterType::DECAY, "B_Ks", 10},
        ParamId{ParameterType::DECAY, "B_Ks", 11},
        ParamId{ParameterType::DECAY, "B_Ks", {12, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {12, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", 14},
        ParamId{ParameterType::DECAY, "B_Ks", {15, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {15, 2}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 1, 0}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 1, 1}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 1, 2}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 2, 0}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 2, 1}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 2, 2}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 3, 0}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 3, 1}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 3, 2}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 4, 0}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 4, 1}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 4, 2}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 5, 0}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 5, 1}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 5, 2}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 6, 0}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 6, 1}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 6, 2}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 7, 0}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 7, 1}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 7, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 1, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 1, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 1, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 2, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 2, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 2, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 3, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 3, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 4, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 4, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 4, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 5, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 5, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 5, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 6, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 6, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 7, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 7, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 7, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 1, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 1, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 1, 3}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 1, 4}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 1, 5}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 1, 6}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 2, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 2, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 2, 3}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 2, 4}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 2, 5}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 2, 6}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 3}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 4}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 5}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 6}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 7}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 3, 8}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 4, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 4, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 4, 3}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 4, 4}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 4, 5}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 4, 6}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 5, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 5, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 5, 3}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 5, 4}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 5, 5}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 5, 6}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 3}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 4}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 5}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 6}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 7}},
        ParamId{ParameterType::DECAY, "B_Ks", {18, 6, 8}},
        // Non-factorizable / power-correction inputs used by BCvDV and KMPW implementations.
        ParamId{ParameterType::DECAY, "B_Ks", {19, 1, 1, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 1, 1, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 1, 1, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 1, 2, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 1, 2, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 1, 2, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 2, 1, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 2, 1, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 2, 1, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 2, 2, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 2, 2, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 2, 2, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 1, 3, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 1, 3, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 2, 3, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {19, 2, 3, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {20, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {20, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {20, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {21, 1, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {21, 1, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {21, 1, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {21, 2, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {21, 2, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {21, 2, 2}},
    }},
    {DecayMapper::to_id(Decays::B__Kstar_gamma), {
        ParamId{ParameterType::FLAVOR, "FMASS", 511},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FLIFE", 511},
        ParamId{ParameterType::FLAVOR, "FLIFE", 521},
        ParamId{ParameterType::FLAVOR, "FMASS", 313},
        ParamId{ParameterType::FLAVOR, "FMASS", 323},
        ParamId{ParameterType::FLAVOR, "FCONST", {313, 1}},
        ParamId{ParameterType::FLAVOR, "FCONST", {313, 2}},
        ParamId{ParameterType::FLAVOR, "FCONST", {323, 1}},
        ParamId{ParameterType::FLAVOR, "FCONST", {323, 2}},
        ParamId{ParameterType::FLAVOR, "FCONST", {511, 1}},
        ParamId{ParameterType::FLAVOR, "FCONST", {521, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", 13},
        ParamId{ParameterType::DECAY, "B_Ks", 14},
        ParamId{ParameterType::DECAY, "B_Ks", 17},
        ParamId{ParameterType::DECAY, "B_Ks", {7, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {7, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {8, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {8, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", 9},
        ParamId{ParameterType::DECAY, "B_Ks", 10},
        ParamId{ParameterType::DECAY, "B_Ks", 11},
        ParamId{ParameterType::DECAY, "B_Ks", {12, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {12, 2}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 1, 0}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 1, 1}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 1, 2}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 2, 0}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 2, 1}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 2, 2}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 3, 0}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 3, 1}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 3, 2}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 4, 0}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 4, 1}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 4, 2}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 5, 0}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 5, 1}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 5, 2}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 6, 0}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 6, 1}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 6, 2}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 7, 0}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 7, 1}},
        // ParamId{ParameterType::DECAY, "B_Ks", {1, 7, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 1, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 1, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 1, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 2, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 2, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 2, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 3, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 3, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 4, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 4, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 4, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 5, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 5, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 5, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 6, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 6, 2}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 7, 0}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 7, 1}},
        ParamId{ParameterType::DECAY, "B_Ks", {3, 7, 2}},
    }},
    {DecayMapper::to_id(Decays::B__l_l), {
        ParamId{ParameterType::FLAVOR, "FMASS", 531},
        ParamId{ParameterType::FLAVOR, "FMASS", 511},
        ParamId{ParameterType::FLAVOR, "FLIFE", 531},
        ParamId{ParameterType::FLAVOR, "FLIFE", 511},
        ParamId{ParameterType::FLAVOR, "FCONST", {511, 1}},
        ParamId{ParameterType::FLAVOR, "FCONST", {531, 1}},
        ParamId{ParameterType::DECAY, "B_ll", 1},
        ParamId{ParameterType::DECAY, "B_ll", 2},
    }},
    {DecayMapper::to_id(Decays::B__l_nu), {
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FLIFE", 521},
        ParamId{ParameterType::FLAVOR, "FCONST", {521, 1}}
    }},
    {DecayMapper::to_id(Decays::Bs__phi_l_l), {
        ParamId{ParameterType::FLAVOR, "FMASS", 531},
        ParamId{ParameterType::FLAVOR, "FLIFE", 531},
        ParamId{ParameterType::FLAVOR, "FMASS", 333},
        ParamId{ParameterType::FLAVOR, "FCONST", {333, 1}},
        ParamId{ParameterType::FLAVOR, "FCONST", {333, 2}},
        ParamId{ParameterType::DECAY, "B_ll", 1},
        ParamId{ParameterType::DECAY, "B_phi", {7, 1}},
        ParamId{ParameterType::DECAY, "B_phi", {7, 2}},
        ParamId{ParameterType::DECAY, "B_phi", {8, 1}},
        ParamId{ParameterType::DECAY, "B_phi", {8, 2}},
        ParamId{ParameterType::DECAY, "B_phi", 9},
        ParamId{ParameterType::DECAY, "B_phi", 10},
        ParamId{ParameterType::DECAY, "B_phi", 11},
        ParamId{ParameterType::DECAY, "B_phi", {12, 1}},
        ParamId{ParameterType::DECAY, "B_phi", {12, 2}},
        ParamId{ParameterType::DECAY, "B_phi", 14},
        ParamId{ParameterType::DECAY, "B_phi", {15, 1}},
        ParamId{ParameterType::DECAY, "B_phi", {15, 2}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 1, 0}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 1, 1}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 1, 2}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 2, 0}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 2, 1}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 2, 2}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 3, 0}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 3, 1}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 3, 2}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 4, 0}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 4, 1}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 4, 2}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 5, 0}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 5, 1}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 5, 2}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 6, 0}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 6, 1}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 6, 2}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 7, 0}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 7, 1}},
        // ParamId{ParameterType::DECAY, "B_phi", {1, 7, 2}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 1, 0}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 1, 1}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 1, 2}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 2, 0}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 2, 1}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 2, 2}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 3, 1}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 3, 2}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 4, 0}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 4, 1}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 4, 2}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 5, 0}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 5, 1}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 5, 2}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 6, 1}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 6, 2}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 7, 0}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 7, 1}},
        ParamId{ParameterType::DECAY, "B_phi", {3, 7, 2}},
        // Power-correction inputs used directly in BsPhiDecay::load_params().
        ParamId{ParameterType::DECAY, "B_phi", {18, 1, 1}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 1, 2}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 1, 3}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 1, 4}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 1, 5}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 1, 6}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 2, 1}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 2, 2}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 2, 3}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 2, 4}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 2, 5}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 2, 6}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 3, 1}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 3, 2}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 3, 3}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 3, 4}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 3, 5}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 3, 6}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 3, 7}},
        ParamId{ParameterType::DECAY, "B_phi", {18, 3, 8}},
    }},
    {DecayMapper::to_id(Decays::B__Xs_gamma), {
        ParamId{ParameterType::DECAY, "B_Xs", 2},
        ParamId{ParameterType::DECAY, "B_Xs", 3},
        ParamId{ParameterType::DECAY, "B_Xs", 4},
        ParamId{ParameterType::DECAY, "B_Xs", 5},
        ParamId{ParameterType::DECAY, "B_Xs", 6},
        ParamId{ParameterType::DECAY, "B_Xs", 7},
        ParamId{ParameterType::DECAY, "B_Xs", 10},
    }},
    {DecayMapper::to_id(Decays::B__Xs_l_l), {
        ParamId{ParameterType::FLAVOR, "FMASS", 421},
        ParamId{ParameterType::DECAY, "B_Xs", 2},
        ParamId{ParameterType::DECAY, "B_Xs", 6},
        ParamId{ParameterType::DECAY, "B_Xsll", 1},
        ParamId{ParameterType::DECAY, "B_Xsll", 2},
        ParamId{ParameterType::DECAY, "B_Xsll", {3, 11, 0}},
        ParamId{ParameterType::DECAY, "B_Xsll", {3, 11, 1}},
        ParamId{ParameterType::DECAY, "B_Xsll", {3, 11, 2}},
        ParamId{ParameterType::DECAY, "B_Xsll", {3, 13, 0}},
        ParamId{ParameterType::DECAY, "B_Xsll", {3, 13, 1}},
        ParamId{ParameterType::DECAY, "B_Xsll", {3, 13, 2}},
    }},
    {DecayMapper::to_id(Decays::D__l_nu), {
        ParamId{ParameterType::FLAVOR, "FMASS", 411},
        ParamId{ParameterType::FLAVOR, "FLIFE", 411},
        ParamId{ParameterType::FLAVOR, "FCONST", {411, 1}}
    }},
    {DecayMapper::to_id(Decays::Ds__l_nu), {
        ParamId{ParameterType::FLAVOR, "FMASS", 431},
        ParamId{ParameterType::FLAVOR, "FLIFE", 431},
        ParamId{ParameterType::FLAVOR, "FCONST", {431, 1}}
    }},
    {DecayMapper::to_id(Decays::K__l_l), {
        ParamId{ParameterType::FLAVOR, "FMASS", 111},
        ParamId{ParameterType::FLAVOR, "FMASS", 113},
        ParamId{ParameterType::FLAVOR, "FMASS", 311},
        ParamId{ParameterType::FLAVOR, "FCONST", {311, 1}},
        ParamId{ParameterType::FLAVOR, "FLIFE", 130},
        ParamId{ParameterType::FLAVOR, "FLIFE", 310},
        ParamId{ParameterType::DECAY, "K_ll", 1},
        ParamId{ParameterType::DECAY, "K_ll", 2},
        ParamId{ParameterType::DECAY, "K_ll", 3},
        ParamId{ParameterType::DECAY, "K_ll", 4},
    }},
    {DecayMapper::to_id(Decays::K__l_nu), {
        ParamId{ParameterType::DECAY, "K_lnu", 1},
        ParamId{ParameterType::FLAVOR, "FMASS", 321},
        ParamId{ParameterType::FLAVOR, "FLIFE", 321},
        ParamId{ParameterType::FLAVOR, "FCONST", {321, 1}},
        ParamId{ParameterType::FLAVOR, "FMASS", 211},
        ParamId{ParameterType::FLAVOR, "FLIFE", 211},
        ParamId{ParameterType::FLAVOR, "FCONST", {211, 1}},
        ParamId{ParameterType::FLAVOR, "FCONSTRATIO", {321, 211, 1, 1}}
    }},
    {DecayMapper::to_id(Decays::K__pi_nu_nu), {
        ParamId{ParameterType::DECAY, "K_pi", 1},
        ParamId{ParameterType::DECAY, "K_pi", 2},
        ParamId{ParameterType::DECAY, "K_pi", 3},
    }},
    {DecayMapper::to_id(Decays::Lambda_b__Lambda_l_l), {
        ParamId{ParameterType::FLAVOR, "FMASS", 321},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FMASS", 5122},
        ParamId{ParameterType::FLAVOR, "FMASS", 3122},
        ParamId{ParameterType::FLAVOR, "FLIFE", 5122},
        ParamId{ParameterType::DECAY, "Lb_L", 8},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 1, 0}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 1, 1}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 1, 2}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 2, 0}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 2, 1}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 2, 2}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 3, 0}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 3, 1}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 3, 2}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 4, 0}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 4, 1}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 4, 2}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 5, 0}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 5, 1}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 5, 2}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 6, 0}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 6, 1}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 6, 2}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 7, 0}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 7, 1}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 7, 2}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 8, 0}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 8, 1}},
        ParamId{ParameterType::DECAY, "Lb_L", {1, 8, 2}},
    }},
    {DecayMapper::to_id(Decays::M0_Mix), {
        ParamId{ParameterType::FLAVOR, "FMASS", 311},
        ParamId{ParameterType::FLAVOR, "FMASS", 421},
        ParamId{ParameterType::FLAVOR, "FMASS", 511},
        ParamId{ParameterType::FLAVOR, "FMASS", 531},
        ParamId{ParameterType::FLAVOR, "FLIFE", 421},
        ParamId{ParameterType::DECAY, "M0_Mix", 1},
        ParamId{ParameterType::DECAY, "M0_Mix", 2},
        ParamId{ParameterType::DECAY, "M0_Mix", 3},
        ParamId{ParameterType::DECAY, "M0_Mix", {4, 1}},
        ParamId{ParameterType::DECAY, "M0_Mix", {4, 2}},
        ParamId{ParameterType::DECAY, "M0_Mix", {4, 3}},
        ParamId{ParameterType::DECAY, "M0_Mix", {4, 4}},
        ParamId{ParameterType::DECAY, "M0_Mix", {4, 5}},
        ParamId{ParameterType::DECAY, "M0_Mix", 6},
        ParamId{ParameterType::DECAY, "M0_Mix", 7},
        ParamId{ParameterType::DECAY, "M0_Mix", 11},
        ParamId{ParameterType::DECAY, "M0_Mix", 12},
    }}
};

std::unordered_set<ParamId> DependenciesHelper::get_allowed_parameters(Observables id) {
    ObservableId obs_id = ObservableMapper::to_id(id);

    return get_allowed_parameters(obs_id);
}

bool DependenciesHelper::is_param_allowed(Observables id, ParamId pid) {
    ObservableId obs_id = ObservableMapper::to_id(id);

    return is_param_allowed(obs_id, pid);
}

std::unordered_set<ParamId> DependenciesHelper::get_allowed_parameters(ObservableId id) {
    std::optional<DecayId> did = DecayMapper::get_decay_id(id);
    if (!did.has_value()) {
        LOG_WARN("No decay found for obs", id.str());
        return {};
    }

    if (did.has_value()) {
        auto decay_deps = dep_lists.at(did.value());
        decay_deps.insert(common_deps.begin(), common_deps.end());
        return decay_deps;
    } else {
        LOG_ERROR("ValueError", "Observable", ObservableMapper::str(id), "doesn't belong to any declared decay.");
    }
}

bool DependenciesHelper::is_param_allowed(ObservableId id, ParamId pid) {
    auto allowed = get_allowed_parameters(id);
    return std::find(allowed.begin(), allowed.end(), pid) != allowed.end();
}
