#ifndef GENERAL_ENUM_H
#define GENERAL_ENUM_H

enum class Observables {
    /* For debugging purposes */
    TEST,
    /* Rare B decays */
    // B > l l
    BR_BS_MUMU,
    BR_BS_MUMU_UNTAG,
    BR_BD_MUMU,
    BR_BS_EE,
    BR_BS_EE_UNTAG,
    BR_BD_EE,
    // B > l nu
    R_TAU_NU,
    BR_BU_TAU_NU,
    // B > K* gamma
    IA_B0__KSTAR0_GAMMA,
    BR_B0__KSTAR0_GAMMA,
    IA_B__KSTAR_GAMMA,
    BR_B__KSTAR_GAMMA,
    // b > s gamma
    BR_B_XS_GAMMA,
    // B > D l nu
    BR_B__D0_TAU_NU,
    A_FB_B__D0_TAU_NU,
    P_TAU_B__D0_TAU_NU,
    R_D0,
    BR_B0__D_TAU_NU,
    A_FB_B0__D_TAU_NU,
    P_TAU_B0__D_TAU_NU,
    R_D,
    // B > D* l nu
    BR_B__DSTAR0_TAU_NU,
    A_FB_B__DSTAR0_TAU_NU,
    P_TAU_B__DSTAR0_TAU_NU,
    P_D_B__DSTAR0_TAU_NU,
    R_DSTAR0,
    BR_B0__DSTAR_TAU_NU,
    A_FB_B0__DSTAR_TAU_NU,
    P_TAU_B0__DSTAR_TAU_NU,
    P_D_B0__DSTAR_TAU_NU,
    R_DSTAR,
    // b > s l l 
    BR_B__Xs_e_e,
    BR_B__Xs_mu_mu,
    BR_B__Xs_tau_tau,
    A_FB_B__Xs_e_e,
    A_FB_B__Xs_mu_mu,
    A_FB_B__Xs_tau_tau,
    // B > K* l l 
    DBR_DQ2_B__KSTAR_E_E,
    A_FB_B__KSTAR_E_E,
    A_FB_CPV_B__KSTAR_E_E,
    Q0_A_FB_B__KSTAR_E_E,
    A_CP_B__KSTAR_E_E,
    F_L_B__KSTAR_E_E,
    F_T_B__KSTAR_E_E,
    A_T_1_B__KSTAR_E_E,
    A_T_2_B__KSTAR_E_E,
    A_T_3_B__KSTAR_E_E,
    A_T_4_B__KSTAR_E_E,
    A_T_5_B__KSTAR_E_E,
    A_T_RE_B__KSTAR_E_E,
    A_T_RE_CPV_B__KSTAR_E_E,
    A_IM_B__KSTAR_E_E,
    ALPHA_K_B__KSTAR_E_E,
    H_T_1_B__KSTAR_E_E,
    H_T_2_B__KSTAR_E_E,
    H_T_3_B__KSTAR_E_E,
    P_1_B__KSTAR_E_E,
    P_2_B__KSTAR_E_E,
    P_3_B__KSTAR_E_E,
    P_4_B__KSTAR_E_E,
    P_5_B__KSTAR_E_E,
    P_6_B__KSTAR_E_E,
    P_8_B__KSTAR_E_E,
    P_PRIME_4_B__KSTAR_E_E,
    P_PRIME_5_B__KSTAR_E_E,
    P_PRIME_6_B__KSTAR_E_E,
    P_PRIME_8_B__KSTAR_E_E,
    S_1C_B__KSTAR_E_E,
    S_2C_B__KSTAR_E_E,
    S_2S_B__KSTAR_E_E,
    S_3_B__KSTAR_E_E,
    S_4_B__KSTAR_E_E,
    S_5_B__KSTAR_E_E,
    S_6C_B__KSTAR_E_E,
    S_7_B__KSTAR_E_E,
    S_8_B__KSTAR_E_E,
    S_9_B__KSTAR_E_E,
    A_1C_B__KSTAR_E_E,
    A_FL_B__KSTAR_E_E,
    A_2S_B__KSTAR_E_E,
    A_3_B__KSTAR_E_E,
    A_4_B__KSTAR_E_E,
    A_5_B__KSTAR_E_E,
    A_6S_B__KSTAR_E_E,
    A_6C_B__KSTAR_E_E,
    A_7_B__KSTAR_E_E,
    A_8_B__KSTAR_E_E,
    A_9_B__KSTAR_E_E,
    P_1_CPV_B__KSTAR_E_E,
    P_2_CPV_B__KSTAR_E_E,
    P_3_CPV_B__KSTAR_E_E,
    P_PRIME_4_CPV_B__KSTAR_E_E,
    P_PRIME_5_CPV_B__KSTAR_E_E,
    P_PRIME_6_CPV_B__KSTAR_E_E,
    P_PRIME_8_CPV_B__KSTAR_E_E,

    DBR_DQ2_B__KSTAR_MU_MU,
    A_FB_B__KSTAR_MU_MU,
    A_FB_CPV_B__KSTAR_MU_MU,
    Q0_A_FB_B__KSTAR_MU_MU,
    A_CP_B__KSTAR_MU_MU,
    F_L_B__KSTAR_MU_MU,
    F_T_B__KSTAR_MU_MU,
    A_T_1_B__KSTAR_MU_MU,
    A_T_2_B__KSTAR_MU_MU,
    A_T_3_B__KSTAR_MU_MU,
    A_T_4_B__KSTAR_MU_MU,
    A_T_5_B__KSTAR_MU_MU,
    A_T_RE_B__KSTAR_MU_MU,
    A_T_RE_CPV_B__KSTAR_MU_MU,
    A_IM_B__KSTAR_MU_MU,
    ALPHA_K_B__KSTAR_MU_MU,
    H_T_1_B__KSTAR_MU_MU,
    H_T_2_B__KSTAR_MU_MU,
    H_T_3_B__KSTAR_MU_MU,
    P_1_B__KSTAR_MU_MU,
    P_2_B__KSTAR_MU_MU,
    P_3_B__KSTAR_MU_MU,
    P_4_B__KSTAR_MU_MU,
    P_5_B__KSTAR_MU_MU,
    P_6_B__KSTAR_MU_MU,
    P_8_B__KSTAR_MU_MU,
    P_PRIME_4_B__KSTAR_MU_MU,
    P_PRIME_5_B__KSTAR_MU_MU,
    P_PRIME_6_B__KSTAR_MU_MU,
    P_PRIME_8_B__KSTAR_MU_MU,
    S_1C_B__KSTAR_MU_MU,
    S_2C_B__KSTAR_MU_MU,
    S_2S_B__KSTAR_MU_MU,
    S_3_B__KSTAR_MU_MU,
    S_4_B__KSTAR_MU_MU,
    S_5_B__KSTAR_MU_MU,
    S_6C_B__KSTAR_MU_MU,
    S_7_B__KSTAR_MU_MU,
    S_8_B__KSTAR_MU_MU,
    S_9_B__KSTAR_MU_MU,
    A_1C_B__KSTAR_MU_MU,
    A_FL_B__KSTAR_MU_MU,
    A_2S_B__KSTAR_MU_MU,
    A_3_B__KSTAR_MU_MU,
    A_4_B__KSTAR_MU_MU,
    A_5_B__KSTAR_MU_MU,
    A_6S_B__KSTAR_MU_MU,
    A_6C_B__KSTAR_MU_MU,
    A_7_B__KSTAR_MU_MU,
    A_8_B__KSTAR_MU_MU,
    A_9_B__KSTAR_MU_MU,
    P_1_CPV_B__KSTAR_MU_MU,
    P_2_CPV_B__KSTAR_MU_MU,
    P_3_CPV_B__KSTAR_MU_MU,
    P_PRIME_4_CPV_B__KSTAR_MU_MU,
    P_PRIME_5_CPV_B__KSTAR_MU_MU,
    P_PRIME_6_CPV_B__KSTAR_MU_MU,
    P_PRIME_8_CPV_B__KSTAR_MU_MU,

    DBR_DQ2_B__KSTAR_TAU_TAU,
    A_FB_B__KSTAR_TAU_TAU,
    A_FB_CPV_B__KSTAR_TAU_TAU,
    Q0_A_FB_B__KSTAR_TAU_TAU,
    A_CP_B__KSTAR_TAU_TAU,
    F_L_B__KSTAR_TAU_TAU,
    F_T_B__KSTAR_TAU_TAU,
    A_T_1_B__KSTAR_TAU_TAU,
    A_T_2_B__KSTAR_TAU_TAU,
    A_T_3_B__KSTAR_TAU_TAU,
    A_T_4_B__KSTAR_TAU_TAU,
    A_T_5_B__KSTAR_TAU_TAU,
    A_T_RE_B__KSTAR_TAU_TAU,
    A_T_RE_CPV_B__KSTAR_TAU_TAU,
    A_IM_B__KSTAR_TAU_TAU,
    ALPHA_K_B__KSTAR_TAU_TAU,
    H_T_1_B__KSTAR_TAU_TAU,
    H_T_2_B__KSTAR_TAU_TAU,
    H_T_3_B__KSTAR_TAU_TAU,
    P_1_B__KSTAR_TAU_TAU,
    P_2_B__KSTAR_TAU_TAU,
    P_3_B__KSTAR_TAU_TAU,
    P_4_B__KSTAR_TAU_TAU,
    P_5_B__KSTAR_TAU_TAU,
    P_6_B__KSTAR_TAU_TAU,
    P_8_B__KSTAR_TAU_TAU,
    P_PRIME_4_B__KSTAR_TAU_TAU,
    P_PRIME_5_B__KSTAR_TAU_TAU,
    P_PRIME_6_B__KSTAR_TAU_TAU,
    P_PRIME_8_B__KSTAR_TAU_TAU,
    S_1C_B__KSTAR_TAU_TAU,
    S_2C_B__KSTAR_TAU_TAU,
    S_2S_B__KSTAR_TAU_TAU,
    S_3_B__KSTAR_TAU_TAU,
    S_4_B__KSTAR_TAU_TAU,
    S_5_B__KSTAR_TAU_TAU,
    S_6C_B__KSTAR_TAU_TAU,
    S_7_B__KSTAR_TAU_TAU,
    S_8_B__KSTAR_TAU_TAU,
    S_9_B__KSTAR_TAU_TAU,
    A_1C_B__KSTAR_TAU_TAU,
    A_FL_B__KSTAR_TAU_TAU,
    A_2S_B__KSTAR_TAU_TAU,
    A_3_B__KSTAR_TAU_TAU,
    A_4_B__KSTAR_TAU_TAU,
    A_5_B__KSTAR_TAU_TAU,
    A_6S_B__KSTAR_TAU_TAU,
    A_6C_B__KSTAR_TAU_TAU,
    A_7_B__KSTAR_TAU_TAU,
    A_8_B__KSTAR_TAU_TAU,
    A_9_B__KSTAR_TAU_TAU,
    P_1_CPV_B__KSTAR_TAU_TAU,
    P_2_CPV_B__KSTAR_TAU_TAU,
    P_3_CPV_B__KSTAR_TAU_TAU,
    P_PRIME_4_CPV_B__KSTAR_TAU_TAU,
    P_PRIME_5_CPV_B__KSTAR_TAU_TAU,
    P_PRIME_6_CPV_B__KSTAR_TAU_TAU,
    P_PRIME_8_CPV_B__KSTAR_TAU_TAU,

    DBR_DQ2_B0__KSTAR0_E_E,
    A_FB_B0__KSTAR0_E_E,
    A_FB_CPV_B0__KSTAR0_E_E,
    Q0_A_FB_B0__KSTAR0_E_E,
    A_CP_B0__KSTAR0_E_E,
    F_L_B0__KSTAR0_E_E,
    F_T_B0__KSTAR0_E_E,
    A_T_1_B0__KSTAR0_E_E,
    A_T_2_B0__KSTAR0_E_E,
    A_T_3_B0__KSTAR0_E_E,
    A_T_4_B0__KSTAR0_E_E,
    A_T_5_B0__KSTAR0_E_E,
    A_T_RE_B0__KSTAR0_E_E,
    A_T_RE_CPV_B0__KSTAR0_E_E,
    A_IM_B0__KSTAR0_E_E,
    ALPHA_K_B0__KSTAR0_E_E,
    H_T_1_B0__KSTAR0_E_E,
    H_T_2_B0__KSTAR0_E_E,
    H_T_3_B0__KSTAR0_E_E,
    P_1_B0__KSTAR0_E_E,
    P_2_B0__KSTAR0_E_E,
    P_3_B0__KSTAR0_E_E,
    P_4_B0__KSTAR0_E_E,
    P_5_B0__KSTAR0_E_E,
    P_6_B0__KSTAR0_E_E,
    P_8_B0__KSTAR0_E_E,
    P_PRIME_4_B0__KSTAR0_E_E,
    P_PRIME_5_B0__KSTAR0_E_E,
    P_PRIME_6_B0__KSTAR0_E_E,
    P_PRIME_8_B0__KSTAR0_E_E,
    S_1C_B0__KSTAR0_E_E,
    S_2C_B0__KSTAR0_E_E,
    S_2S_B0__KSTAR0_E_E,
    S_3_B0__KSTAR0_E_E,
    S_4_B0__KSTAR0_E_E,
    S_5_B0__KSTAR0_E_E,
    S_6C_B0__KSTAR0_E_E,
    S_7_B0__KSTAR0_E_E,
    S_8_B0__KSTAR0_E_E,
    S_9_B0__KSTAR0_E_E,
    A_1C_B0__KSTAR0_E_E,
    A_FL_B0__KSTAR0_E_E,
    A_2S_B0__KSTAR0_E_E,
    A_3_B0__KSTAR0_E_E,
    A_4_B0__KSTAR0_E_E,
    A_5_B0__KSTAR0_E_E,
    A_6S_B0__KSTAR0_E_E,
    A_6C_B0__KSTAR0_E_E,
    A_7_B0__KSTAR0_E_E,
    A_8_B0__KSTAR0_E_E,
    A_9_B0__KSTAR0_E_E,
    P_1_CPV_B0__KSTAR0_E_E,
    P_2_CPV_B0__KSTAR0_E_E,
    P_3_CPV_B0__KSTAR0_E_E,
    P_PRIME_4_CPV_B0__KSTAR0_E_E,
    P_PRIME_5_CPV_B0__KSTAR0_E_E,
    P_PRIME_6_CPV_B0__KSTAR0_E_E,
    P_PRIME_8_CPV_B0__KSTAR0_E_E,

    DBR_DQ2_B0__KSTAR0_MU_MU,
    A_FB_B0__KSTAR0_MU_MU,
    A_FB_CPV_B0__KSTAR0_MU_MU,
    Q0_A_FB_B0__KSTAR0_MU_MU,
    A_CP_B0__KSTAR0_MU_MU,
    F_L_B0__KSTAR0_MU_MU,
    F_T_B0__KSTAR0_MU_MU,
    A_T_1_B0__KSTAR0_MU_MU,
    A_T_2_B0__KSTAR0_MU_MU,
    A_T_3_B0__KSTAR0_MU_MU,
    A_T_4_B0__KSTAR0_MU_MU,
    A_T_5_B0__KSTAR0_MU_MU,
    A_T_RE_B0__KSTAR0_MU_MU,
    A_T_RE_CPV_B0__KSTAR0_MU_MU,
    A_IM_B0__KSTAR0_MU_MU,
    ALPHA_K_B0__KSTAR0_MU_MU,
    H_T_1_B0__KSTAR0_MU_MU,
    H_T_2_B0__KSTAR0_MU_MU,
    H_T_3_B0__KSTAR0_MU_MU,
    P_1_B0__KSTAR0_MU_MU,
    P_2_B0__KSTAR0_MU_MU,
    P_3_B0__KSTAR0_MU_MU,
    P_4_B0__KSTAR0_MU_MU,
    P_5_B0__KSTAR0_MU_MU,
    P_6_B0__KSTAR0_MU_MU,
    P_8_B0__KSTAR0_MU_MU,
    P_PRIME_4_B0__KSTAR0_MU_MU,
    P_PRIME_5_B0__KSTAR0_MU_MU,
    P_PRIME_6_B0__KSTAR0_MU_MU,
    P_PRIME_8_B0__KSTAR0_MU_MU,
    S_1C_B0__KSTAR0_MU_MU,
    S_2C_B0__KSTAR0_MU_MU,
    S_2S_B0__KSTAR0_MU_MU,
    S_3_B0__KSTAR0_MU_MU,
    S_4_B0__KSTAR0_MU_MU,
    S_5_B0__KSTAR0_MU_MU,
    S_6C_B0__KSTAR0_MU_MU,
    S_7_B0__KSTAR0_MU_MU,
    S_8_B0__KSTAR0_MU_MU,
    S_9_B0__KSTAR0_MU_MU,
    A_1C_B0__KSTAR0_MU_MU,
    A_FL_B0__KSTAR0_MU_MU,
    A_2S_B0__KSTAR0_MU_MU,
    A_3_B0__KSTAR0_MU_MU,
    A_4_B0__KSTAR0_MU_MU,
    A_5_B0__KSTAR0_MU_MU,
    A_6S_B0__KSTAR0_MU_MU,
    A_6C_B0__KSTAR0_MU_MU,
    A_7_B0__KSTAR0_MU_MU,
    A_8_B0__KSTAR0_MU_MU,
    A_9_B0__KSTAR0_MU_MU,
    P_1_CPV_B0__KSTAR0_MU_MU,
    P_2_CPV_B0__KSTAR0_MU_MU,
    P_3_CPV_B0__KSTAR0_MU_MU,
    P_PRIME_4_CPV_B0__KSTAR0_MU_MU,
    P_PRIME_5_CPV_B0__KSTAR0_MU_MU,
    P_PRIME_6_CPV_B0__KSTAR0_MU_MU,
    P_PRIME_8_CPV_B0__KSTAR0_MU_MU,

    DBR_DQ2_B0__KSTAR0_TAU_TAU,
    A_FB_B0__KSTAR0_TAU_TAU,
    A_FB_CPV_B0__KSTAR0_TAU_TAU,
    Q0_A_FB_B0__KSTAR0_TAU_TAU,
    A_CP_B0__KSTAR0_TAU_TAU,
    F_L_B0__KSTAR0_TAU_TAU,
    F_T_B0__KSTAR0_TAU_TAU,
    A_T_1_B0__KSTAR0_TAU_TAU,
    A_T_2_B0__KSTAR0_TAU_TAU,
    A_T_3_B0__KSTAR0_TAU_TAU,
    A_T_4_B0__KSTAR0_TAU_TAU,
    A_T_5_B0__KSTAR0_TAU_TAU,
    A_T_RE_B0__KSTAR0_TAU_TAU,
    A_T_RE_CPV_B0__KSTAR0_TAU_TAU,
    A_IM_B0__KSTAR0_TAU_TAU,
    ALPHA_K_B0__KSTAR0_TAU_TAU,
    H_T_1_B0__KSTAR0_TAU_TAU,
    H_T_2_B0__KSTAR0_TAU_TAU,
    H_T_3_B0__KSTAR0_TAU_TAU,
    P_1_B0__KSTAR0_TAU_TAU,
    P_2_B0__KSTAR0_TAU_TAU,
    P_3_B0__KSTAR0_TAU_TAU,
    P_4_B0__KSTAR0_TAU_TAU,
    P_5_B0__KSTAR0_TAU_TAU,
    P_6_B0__KSTAR0_TAU_TAU,
    P_8_B0__KSTAR0_TAU_TAU,
    P_PRIME_4_B0__KSTAR0_TAU_TAU,
    P_PRIME_5_B0__KSTAR0_TAU_TAU,
    P_PRIME_6_B0__KSTAR0_TAU_TAU,
    P_PRIME_8_B0__KSTAR0_TAU_TAU,
    S_1C_B0__KSTAR0_TAU_TAU,
    S_2C_B0__KSTAR0_TAU_TAU,
    S_2S_B0__KSTAR0_TAU_TAU,
    S_3_B0__KSTAR0_TAU_TAU,
    S_4_B0__KSTAR0_TAU_TAU,
    S_5_B0__KSTAR0_TAU_TAU,
    S_6C_B0__KSTAR0_TAU_TAU,
    S_7_B0__KSTAR0_TAU_TAU,
    S_8_B0__KSTAR0_TAU_TAU,
    S_9_B0__KSTAR0_TAU_TAU,
    A_1C_B0__KSTAR0_TAU_TAU,
    A_FL_B0__KSTAR0_TAU_TAU,
    A_2S_B0__KSTAR0_TAU_TAU,
    A_3_B0__KSTAR0_TAU_TAU,
    A_4_B0__KSTAR0_TAU_TAU,
    A_5_B0__KSTAR0_TAU_TAU,
    A_6S_B0__KSTAR0_TAU_TAU,
    A_6C_B0__KSTAR0_TAU_TAU,
    A_7_B0__KSTAR0_TAU_TAU,
    A_8_B0__KSTAR0_TAU_TAU,
    A_9_B0__KSTAR0_TAU_TAU,
    P_1_CPV_B0__KSTAR0_TAU_TAU,
    P_2_CPV_B0__KSTAR0_TAU_TAU,
    P_3_CPV_B0__KSTAR0_TAU_TAU,
    P_PRIME_4_CPV_B0__KSTAR0_TAU_TAU,
    P_PRIME_5_CPV_B0__KSTAR0_TAU_TAU,
    P_PRIME_6_CPV_B0__KSTAR0_TAU_TAU,
    P_PRIME_8_CPV_B0__KSTAR0_TAU_TAU,
    // Bs > phi l l
    DBR_DQ2_BS__PHI_E_E,
    A_FB_CPV_BS__PHI_E_E,
    F_L_BS_PHI_E_E,
    A_T_2_BS_PHI_E_E,
    A_T_RE_CPV_BS_PHI_E_E,
    A_T_IM_CPV_BS_PHI_E_E,
    P_PRIME_4_BS_PHI_E_E,
    P_PRIME_6_BS_PHI_E_E,
    S_2S_BS_PHI_E_E,
    S_3_BS_PHI_E_E,
    S_4_BS_PHI_E_E,
    S_7_BS_PHI_E_E,
    A_5_BS_PHI_E_E,
    A_6C_BS_PHI_E_E,
    A_8_BS_PHI_E_E,
    A_9_BS_PHI_E_E,
    P_2_CPV_BS_PHI_E_E,
    P_3_CPV_BS_PHI_E_E,
    P_PRIME_5_CPV_BS_PHI_E_E,
    P_PRIME_8_CPV_BS_PHI_E_E,
    Q_8M_BS_PHI_E_E,
    Q_8P_BS_PHI_E_E,
    Q_9_BS_PHI_E_E,
    DBR_DQ2_BS__PHI_MU_MU,
    A_FB_CPV_BS__PHI_MU_MU,
    F_L_BS_PHI_MU_MU,
    A_T_2_BS_PHI_MU_MU,
    A_T_RE_CPV_BS_PHI_MU_MU,
    A_T_IM_CPV_BS_PHI_MU_MU,
    P_PRIME_4_BS_PHI_MU_MU,
    P_PRIME_6_BS_PHI_MU_MU,
    S_2S_BS_PHI_MU_MU,
    S_3_BS_PHI_MU_MU,
    S_4_BS_PHI_MU_MU,
    S_7_BS_PHI_MU_MU,
    A_5_BS_PHI_MU_MU,
    A_6C_BS_PHI_MU_MU,
    A_8_BS_PHI_MU_MU,
    A_9_BS_PHI_MU_MU,
    P_2_CPV_BS_PHI_MU_MU,
    P_3_CPV_BS_PHI_MU_MU,
    P_PRIME_5_CPV_BS_PHI_MU_MU,
    P_PRIME_8_CPV_BS_PHI_MU_MU,
    Q_8M_BS_PHI_MU_MU,
    Q_8P_BS_PHI_MU_MU,
    Q_9_BS_PHI_MU_MU,
    DBR_DQ2_BS__PHI_TAU_TAU,
    A_FB_CPV_BS__PHI_TAU_TAU,
    F_L_BS_PHI_TAU_TAU,
    A_T_2_BS_PHI_TAU_TAU,
    A_T_RE_CPV_BS_PHI_TAU_TAU,
    A_T_IM_CPV_BS_PHI_TAU_TAU,
    P_PRIME_4_BS_PHI_TAU_TAU,
    P_PRIME_6_BS_PHI_TAU_TAU,
    S_2S_BS_PHI_TAU_TAU,
    S_3_BS_PHI_TAU_TAU,
    S_4_BS_PHI_TAU_TAU,
    S_7_BS_PHI_TAU_TAU,
    A_5_BS_PHI_TAU_TAU,
    A_6C_BS_PHI_TAU_TAU,
    A_8_BS_PHI_TAU_TAU,
    A_9_BS_PHI_TAU_TAU,
    P_2_CPV_BS_PHI_TAU_TAU,
    P_3_CPV_BS_PHI_TAU_TAU,
    P_PRIME_5_CPV_BS_PHI_TAU_TAU,
    P_PRIME_8_CPV_BS_PHI_TAU_TAU,
    Q_8M_BS_PHI_TAU_TAU,
    Q_8P_BS_PHI_TAU_TAU,
    Q_9_BS_PHI_TAU_TAU,
    // B > K l l
    DBR_DQ2_B0__K0_E_E,
    A_FB_B0__K0_E_E,
    F_H_B0__K0_E_E,
    DBR_DQ2_B__K_E_E,
    A_FB_B__K_E_E,
    F_H_B__K_E_E,
    DBR_DQ2_B0__K0_MU_MU,
    A_FB_B0__K0_MU_MU,
    F_H_B0__K0_MU_MU,
    DBR_DQ2_B__K_MU_MU,
    A_FB_B__K_MU_MU,
    F_H_B__K_MU_MU,
    DBR_DQ2_B0__K0_TAU_TAU,
    A_FB_B0__K0_TAU_TAU,
    F_H_B0__K0_TAU_TAU,
    DBR_DQ2_B__K_TAU_TAU,
    A_FB_B__K_TAU_TAU,
    F_H_B__K_TAU_TAU,
    // Lambda_b > Lambda l l
    DBR_DQ2_LAMBDA_B__LAMBDA_E_E,
    A_FB_L_LAMBDA_B__LAMBDA_E_E,
    A_FB_H_LAMBDA_B__LAMBDA_E_E,
    A_FB_LH_LAMBDA_B__LAMBDA_E_E,
    F_L_LAMBDA_B__LAMBDA_E_E,
    F_T_LAMBDA_B__LAMBDA_E_E,
    DBR_DQ2_LAMBDA_B__LAMBDA_MU_MU,
    A_FB_L_LAMBDA_B__LAMBDA_MU_MU,
    A_FB_H_LAMBDA_B__LAMBDA_MU_MU,
    A_FB_LH_LAMBDA_B__LAMBDA_MU_MU,
    F_L_LAMBDA_B__LAMBDA_MU_MU,
    F_T_LAMBDA_B__LAMBDA_MU_MU,
    DBR_DQ2_LAMBDA_B__LAMBDA_TAU_TAU,
    A_FB_L_LAMBDA_B__LAMBDA_TAU_TAU,
    A_FB_H_LAMBDA_B__LAMBDA_TAU_TAU,
    A_FB_LH_LAMBDA_B__LAMBDA_TAU_TAU,
    F_L_LAMBDA_B__LAMBDA_TAU_TAU,
    F_T_LAMBDA_B__LAMBDA_TAU_TAU,
    /* Neutral Meson Mixing */
    // Bd
    PHI_D,
    DELTA_M_BD,
    // Bs
    PHI_S,
    DELTA_M_BS,
    A_FS,
    // K
    DELTA_M_K,
    ABS_EPSILON_K,
    // D
    X_D,
    /* Rare K decays */
    // K_L,S > mu mu
    BR_KL__MU_MU,
    BR_KS__MU_MU,
    // K > mu nu
    BR_K__MU_NU__BR_PI__MU_NU,
    R_MU23,
    // K > pi nu nu
    BR_K__PI_NU_NU,
    BR_KL__PI0_NU_NU,
    /* Rare D decays */
    BR_D__MU_NU,
    BR_DS__MU_NU,
    BR_DS__TAU_NU,
};

enum class Decays {
    B__D_l_nu, //
    B__Dstar_l_nu, //
    B__Kstar_gamma, //
    B__l_l, //
    B__l_nu, //
    B__Xs_gamma, //
    B__Xs_l_l, //
    B__K_l_l, //
    B__Kstar_l_l, //
    Bs__phi_l_l,
    Lambda_b__Lambda_l_l,
    M0_Mix,
    K__l_l,
    K__pi_nu_nu,
    K__l_nu,
    D__l_nu,
    Ds__l_nu,
};

enum class QCDOrder {
    NONE,
    LO,
    NLO,
    NNLO
};

enum class WCoef {
    C1, C2, C3, C4, C5, C6, C7, C8, C9, C10,                                // b > s l l
    CQ1, CQ2,                                                               // b > s l l
    CP1, CP2, CP3, CP4, CP5, CP6, CP7, CP8, CP9, CP10, CPQ1, CPQ2,          // b > s l l
    C_V1_bc, C_V2_bc, C_S1_bc, C_S2_bc, C_T_bc,                             // b > c l nu
    C_V1_bu, C_V2_bu, C_S1_bu, C_S2_bu, C_T_bu,                             // b > u l nu
    C_V1_cs, C_V2_cs, C_S1_cs, C_S2_cs, C_T_cs,                             // c > s l nu
    C_V1_cd, C_V2_cd, C_S1_cd, C_S2_cd, C_T_cd,                             // c > d l nu
    C_V1_su, C_V2_su, C_S1_su, C_S2_su, C_T_su,                             // s > u l nu
    C_V1_du, C_V2_du, C_S1_du, C_S2_du, C_T_du,                             // d > u l nu
    C_BD_1, CT_BD_1, C_BD_2, CT_BD_2, C_BD_3, CT_BD_3, C_BD_4, C_BD_5,      // Bd0 mixing
    C_BS_1, CT_BS_1, C_BS_2, CT_BS_2, C_BS_3, CT_BS_3, C_BS_4, C_BS_5,      // Bs0 mixing
    C_SD_1, CT_SD_1, C_SD_2, CT_SD_2, C_SD_3, CT_SD_3, C_SD_4, C_SD_5,      // K0 mixing
    C_CU_1, CT_CU_1, C_CU_2, CT_CU_2, C_CU_3, CT_CU_3, C_CU_4, C_CU_5,      // D0 mixing
    CK9, CPK9, CK10, CPK10, CKQ1, CKQ2, CPKQ1, CPKQ2, CK_L                        // s > d l l
};

enum class WGroup {
    B, 
    BPrime, 
    BScalar,
    CC_bc,
    CC_bu,
    CC_cs,
    CC_cd,
    CC_su,
    CC_du,
    MESON_MIXING,
    K
};


enum class ParameterType {
    SM,
    BSM,
    FLAVOR,
    WILSON,
    DECAY,
    PASSTHROUGH,
    OBSERVABLE,
};

enum class Model {
    SM,
    SUSY,
    THDM,
    MARTY
};

enum class WilsonBasis {
    B_STANDARD, 
    B_TRADITIONAL
};

enum class ContributionType {
    SM, 
    BSM,
    TOTAL
};

enum class MassType {
    POLE,
    MSBAR
};

enum class ScaleType {
    MATCHING,
    HADRONIC
};

enum class DataType { 
    VALUE,
    STD_STAT,
    STD_SYST,
    STD_COMBINED
};

enum class UncertaintyType {
    STAT,
    SYST,
    COMBINED
};


#endif