#include "General.h"

const std::map<Observables, std::unordered_set<ParamId>> DependenciesHelper::dep_lists = {
    {Observables::BR_BS_MUMU, {
        ParamId{ParameterType::SM, "SMINPUTS", 1},
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 13},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 2)},
        ParamId{ParameterType::FLAVOR, "FMASS", 531},
        ParamId{ParameterType::FLAVOR, "FLIFE", 531},
        ParamId{ParameterType::FLAVOR, "FCONST", LhaID(531,1)}
    }},
    {Observables::BR_BS_MUMU_UNTAG, {
        ParamId{ParameterType::SM, "SMINPUTS", 1},
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 13},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 2)},
        ParamId{ParameterType::FLAVOR, "FMASS", 531},
        ParamId{ParameterType::FLAVOR, "FLIFE", 531},
        ParamId{ParameterType::FLAVOR, "FCONST", LhaID(531,1)},
        ParamId{ParameterType::DECAY, "B_ll", 1}
    }},
    {Observables::BR_BD_MUMU, {
        ParamId{ParameterType::SM, "SMINPUTS", 1},
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 13},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 2)},
        ParamId{ParameterType::FLAVOR, "FMASS", 511},
        ParamId{ParameterType::FLAVOR, "FLIFE", 511},
        ParamId{ParameterType::FLAVOR, "FCONST", LhaID(511,1)}
    }},
    {Observables::BR_BU_TAU_NU, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 15},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 2)},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FLIFE", 521},
        ParamId{ParameterType::FLAVOR, "FCONST", LhaID(521,1)}
    }},
    {Observables::R_TAU_NU, {
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 15},
        ParamId{ParameterType::FLAVOR, "FMASS", 521}
    }},
    {Observables::ISOSPIN_ASYMMETRY_B_KSTAR_GAMMA, {
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 2)},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FMASS", 323},
        ParamId{ParameterType::FLAVOR, "FCONST", LhaID(521,1)},
        ParamId{ParameterType::FLAVOR, "FCONST", LhaID(323,1)},
        ParamId{ParameterType::FLAVOR, "FCONST", LhaID(323,2)},
        ParamId{ParameterType::DECAY, "B_Ks", 1},
        ParamId{ParameterType::DECAY, "B_Ks", 2},
        ParamId{ParameterType::DECAY, "B_Ks", 3},
        ParamId{ParameterType::DECAY, "B_Ks", 4},
        ParamId{ParameterType::DECAY, "B_Ks", 5},
        ParamId{ParameterType::DECAY, "B_Ks", 6},
        ParamId{ParameterType::DECAY, "B_Ks", 7},
        ParamId{ParameterType::DECAY, "B_Ks", 8},
        ParamId{ParameterType::DECAY, "B_Ks", 9},
        ParamId{ParameterType::DECAY, "B_Ks", 10},
        ParamId{ParameterType::DECAY, "B_Ks", 11},
        ParamId{ParameterType::DECAY, "B_Ks", 12},
        ParamId{ParameterType::DECAY, "B_Ks", 13}
    }},
    {Observables::BR_B_XS_GAMMA, {
        ParamId{ParameterType::SM, "SMINPUTS", 1},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 2)},
        ParamId{ParameterType::DECAY, "B_Xs", 1},
        ParamId{ParameterType::DECAY, "B_Xs", 2},
        ParamId{ParameterType::DECAY, "B_Xs", 3},
        ParamId{ParameterType::DECAY, "B_Xs", 4},
        ParamId{ParameterType::DECAY, "B_Xs", 5},
        ParamId{ParameterType::DECAY, "B_Xs", 6},
        ParamId{ParameterType::DECAY, "B_Xs", 7},
        ParamId{ParameterType::DECAY, "B_Xs", 8},
        ParamId{ParameterType::DECAY, "B_Xs", 9},
    }},
    {Observables::BR_B__D_TAU_NU, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 15},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 2)},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FMASS", 421},
        ParamId{ParameterType::FLAVOR, "FLIFE", 521},
        ParamId{ParameterType::DECAY, "B_Dlnu", 1},
        ParamId{ParameterType::DECAY, "B_Dlnu", 2},
        ParamId{ParameterType::DECAY, "B_Dlnu", 3},
    }},
    {Observables::A_FB_B__D_TAU_NU, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 15},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FMASS", 421},
        ParamId{ParameterType::FLAVOR, "FLIFE", 521},
        ParamId{ParameterType::DECAY, "B_Dlnu", 2},
        ParamId{ParameterType::DECAY, "B_Dlnu", 3},
    }},
    {Observables::P_TAU_B__D_TAU_NU, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 15},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FMASS", 421},
        ParamId{ParameterType::FLAVOR, "FLIFE", 521},
        ParamId{ParameterType::DECAY, "B_Dlnu", 2},
        ParamId{ParameterType::DECAY, "B_Dlnu", 3},
    }},
    {Observables::R_D, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 15},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FMASS", 421},
        ParamId{ParameterType::FLAVOR, "FLIFE", 521},
        ParamId{ParameterType::DECAY, "B_Dlnu", 2},
        ParamId{ParameterType::DECAY, "B_Dlnu", 3},
    }},
    {Observables::BR_B__DSTAR_TAU_NU, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 15},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 2)},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FMASS", 423},
        ParamId{ParameterType::FLAVOR, "FLIFE", 521},
        ParamId{ParameterType::DECAY, "B_Dslnu", 1},
        ParamId{ParameterType::DECAY, "B_Dslnu", 2},
        ParamId{ParameterType::DECAY, "B_Dslnu", 3},
        ParamId{ParameterType::DECAY, "B_Dslnu", 4},
    }},
    {Observables::A_FB_B__DSTAR_TAU_NU, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 15},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FMASS", 423},
        ParamId{ParameterType::FLAVOR, "FLIFE", 521},
        ParamId{ParameterType::DECAY, "B_Dslnu", 2},
        ParamId{ParameterType::DECAY, "B_Dslnu", 3},
        ParamId{ParameterType::DECAY, "B_Dslnu", 4},
    }},
    {Observables::P_TAU_B__DSTAR_TAU_NU, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 15},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FMASS", 423},
        ParamId{ParameterType::FLAVOR, "FLIFE", 521},
        ParamId{ParameterType::DECAY, "B_Dslnu", 2},
        ParamId{ParameterType::DECAY, "B_Dslnu", 3},
        ParamId{ParameterType::DECAY, "B_Dslnu", 4},
    }},
    {Observables::P_D_B__DSTAR_TAU_NU, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 15},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FMASS", 423},
        ParamId{ParameterType::FLAVOR, "FLIFE", 521},
        ParamId{ParameterType::DECAY, "B_Dslnu", 2},
        ParamId{ParameterType::DECAY, "B_Dslnu", 3},
        ParamId{ParameterType::DECAY, "B_Dslnu", 4},
    }},
    {Observables::R_DSTAR, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 15},
        ParamId{ParameterType::FLAVOR, "FMASS", 521},
        ParamId{ParameterType::FLAVOR, "FMASS", 423},
        ParamId{ParameterType::FLAVOR, "FLIFE", 521},
        ParamId{ParameterType::DECAY, "B_Dslnu", 2},
        ParamId{ParameterType::DECAY, "B_Dslnu", 3},
        ParamId{ParameterType::DECAY, "B_Dslnu", 4},
    }},
    {Observables::BR_B__Xs_mu_mu__LOW_Q2, {
        ParamId{ParameterType::SM, "SMINPUTS", 1},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 13},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::WILSON, "B_SCALE", 1},
        ParamId{ParameterType::FLAVOR, "FMASS", 421},
        ParamId{ParameterType::DECAY, "B_Xsll", 1},
        ParamId{ParameterType::DECAY, "B_Xsll", 2},
        ParamId{ParameterType::DECAY, "B_Xsll", 3},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 2)},
    }},
    {Observables::BR_B__Xs_mu_mu__HIGH_Q2, {
        ParamId{ParameterType::SM, "SMINPUTS", 1},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 13},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::WILSON, "B_SCALE", 1},
        ParamId{ParameterType::FLAVOR, "FMASS", 421},
        ParamId{ParameterType::DECAY, "B_Xsll", 1},
        ParamId{ParameterType::DECAY, "B_Xsll", 3},
        ParamId{ParameterType::DECAY, "B_Xsll", 4},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 2)},
    }},
    {Observables::BR_B__Xs_tau_tau__HIGH_Q2, {
        ParamId{ParameterType::SM, "SMINPUTS", 1},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 13},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::WILSON, "B_SCALE", 1},
        ParamId{ParameterType::FLAVOR, "FMASS", 421},
        ParamId{ParameterType::DECAY, "B_Xsll", 1},
        ParamId{ParameterType::DECAY, "B_Xsll", 3},
        ParamId{ParameterType::DECAY, "B_Xsll", 4},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 2)},
    }},
    {Observables::PHI_D, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::FLAVOR, "FMASS", 511},
        ParamId{ParameterType::FLAVOR, "FCONST", {511, 1}},
        ParamId{ParameterType::FLAVOR, "FBAG", {511, 1}},
        ParamId{ParameterType::FLAVOR, "FBAG", {511, 2}},
        ParamId{ParameterType::FLAVOR, "FBAG", {511, 3}},
        ParamId{ParameterType::FLAVOR, "FBAG", {511, 4}},
        ParamId{ParameterType::FLAVOR, "FBAG", {511, 5}},
        ParamId{ParameterType::DECAY, "M0_Mix", 1},
        ParamId{ParameterType::DECAY, "M0_Mix", 8},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 2)},
    }},
    {Observables::DELTA_M_BD, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::FLAVOR, "FMASS", 511},
        ParamId{ParameterType::FLAVOR, "FCONST", {511, 1}},
        ParamId{ParameterType::FLAVOR, "FBAG", {511, 1}},
        ParamId{ParameterType::FLAVOR, "FBAG", {511, 2}},
        ParamId{ParameterType::FLAVOR, "FBAG", {511, 3}},
        ParamId{ParameterType::FLAVOR, "FBAG", {511, 4}},
        ParamId{ParameterType::FLAVOR, "FBAG", {511, 5}},
        ParamId{ParameterType::DECAY, "M0_Mix", 1},
        ParamId{ParameterType::DECAY, "M0_Mix", 8},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 2)},
    }},
    {Observables::PHI_S, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::FLAVOR, "FMASS", 531},
        ParamId{ParameterType::FLAVOR, "FCONST", {531, 1}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 1}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 2}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 3}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 4}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 5}},
        ParamId{ParameterType::DECAY, "M0_Mix", 2},
        ParamId{ParameterType::DECAY, "M0_Mix", 8},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 2)},
    }},
    {Observables::DELTA_M_BS, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::FLAVOR, "FMASS", 531},
        ParamId{ParameterType::FLAVOR, "FCONST", {531, 1}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 1}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 2}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 3}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 4}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 5}},
        ParamId{ParameterType::DECAY, "M0_Mix", 2},
        ParamId{ParameterType::DECAY, "M0_Mix", 8},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 2)},
    }},
    {Observables::A_FS, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::FLAVOR, "FMASS", 531},
        ParamId{ParameterType::FLAVOR, "FCONST", {531, 1}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 1}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 2}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 3}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 4}},
        ParamId{ParameterType::FLAVOR, "FBAG", {531, 5}},
        ParamId{ParameterType::DECAY, "M0_Mix", 2},
        ParamId{ParameterType::DECAY, "M0_Mix", {5, 1}},
        ParamId{ParameterType::DECAY, "M0_Mix", {5, 2}},
        ParamId{ParameterType::DECAY, "M0_Mix", 6},
        ParamId{ParameterType::DECAY, "M0_Mix", 8},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 2)},
    }},
    {Observables::DELTA_M_K, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::FLAVOR, "FMASS", 311},
        ParamId{ParameterType::FLAVOR, "FCONST", {321, 1}},
        ParamId{ParameterType::FLAVOR, "FBAG", {311, 1}},
        ParamId{ParameterType::FLAVOR, "FBAG", {311, 2}},
        ParamId{ParameterType::FLAVOR, "FBAG", {311, 3}},
        ParamId{ParameterType::FLAVOR, "FBAG", {311, 4}},
        ParamId{ParameterType::FLAVOR, "FBAG", {311, 5}},
        ParamId{ParameterType::DECAY, "M0_Mix", 3},
        ParamId{ParameterType::DECAY, "M0_Mix", 9},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 1)},
    }},
    {Observables::ABS_EPSILON_K, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::FLAVOR, "FMASS", 311},
        ParamId{ParameterType::FLAVOR, "FCONST", {321, 1}},
        ParamId{ParameterType::FLAVOR, "FBAG", {311, 1}},
        ParamId{ParameterType::FLAVOR, "FBAG", {311, 2}},
        ParamId{ParameterType::FLAVOR, "FBAG", {311, 3}},
        ParamId{ParameterType::FLAVOR, "FBAG", {311, 4}},
        ParamId{ParameterType::FLAVOR, "FBAG", {311, 5}},
        ParamId{ParameterType::DECAY, "M0_Mix", 3},
        ParamId{ParameterType::DECAY, "M0_Mix", 7},
        ParamId{ParameterType::DECAY, "M0_Mix", 9},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(2, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 1)},
    }},
    {Observables::X_D, {
        ParamId{ParameterType::SM, "SMINPUTS", 2},
        ParamId{ParameterType::SM, "SMINPUTS", 3},
        ParamId{ParameterType::SM, "SMINPUTS", 4},
        ParamId{ParameterType::SM, "SMINPUTS", 5},
        ParamId{ParameterType::SM, "SMINPUTS", 6},
        ParamId{ParameterType::SM, "MASS", 1},
        ParamId{ParameterType::SM, "MASS", 2},
        ParamId{ParameterType::SM, "MASS", 3},
        ParamId{ParameterType::SM, "MASS", 4},
        ParamId{ParameterType::SM, "MASS", 24},
        ParamId{ParameterType::FLAVOR, "FMASS", 421},
        ParamId{ParameterType::DECAY, "M0_Mix", {4, 1}},
        ParamId{ParameterType::DECAY, "M0_Mix", {4, 2}},
        ParamId{ParameterType::DECAY, "M0_Mix", {4, 3}},
        ParamId{ParameterType::DECAY, "M0_Mix", {4, 4}},
        ParamId{ParameterType::DECAY, "M0_Mix", {4, 5}},
        ParamId{ParameterType::DECAY, "M0_Mix", 10},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 0)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 1)},
        ParamId{ParameterType::SM, "VCKM", LhaID(0, 2)},
        ParamId{ParameterType::SM, "VCKM", LhaID(1, 2)},
    }}
};

std::unordered_set<ParamId> DependenciesHelper::get_allowed_parameters(Observables id) {
    return dep_lists.at(id);
}

bool DependenciesHelper::is_param_allowed(Observables id, ParamId pid) {
    auto allowed = dep_lists.at(id);
    return std::find(allowed.begin(), allowed.end(), pid) != allowed.end();
}

const std::map<BlockName, std::vector<std::vector<long>>> LhaParamsHelper::minimal_blocks = {
    {"FMASS", {{211}, {321}, {323}, {411}, {421}, {423}, {431}, {511}, {521}, {531}}},
    {"FLIFE", {{211}, {321}, {323}, {411}, {421}, {431}, {511}, {521}, {531}}},
    {"FCONST", {{511, 1}, {521, 1}, {531, 1}, {323, 1}, {323, 2}}},
};

std::vector<std::vector<long>> LhaParamsHelper::get_minimal_content(const BlockName &block_name) {
    if (LhaParamsHelper::minimal_blocks.contains(block_name)) {
        return LhaParamsHelper::minimal_blocks.at(block_name);
    }
    LOG_ERROR("LhaParamsHelper", "Unknown block", block_name);
}

std::ostream &operator<<(std::ostream &os, const LhaID &id) {
    os << id.to_string();
    return os;
}

LhaID::LhaID(const std::string &str_id) {
    for (const auto &num : split(str_id, '_')) {
        parts.emplace_back(std::stol(num));
    }
}

std::string LhaID::to_string() const {
    std::stringstream ss;
    if (!this->parts.empty()) {
        ss << this->parts.at(0);
        for (size_t i = 1; i < this->parts.size(); i++) {
            ss << '_' << this->parts.at(i);
        }
    }
    return ss.str();
}