#ifndef JOINTDISTRIBUTION_H
#define JOINTDISTRIBUTION_H

#include <cmath>
#include <cstddef>
#include <iomanip>
#include <iostream>
#include <limits>
#include <memory>
#include <random>
#include <stdexcept>
#include <string>
#include <vector>
#include <algorithm>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_linalg.h>

#include "Include.h"
#include "IMarginalDistribution.h"
#include "ICopula.h"
#include "Math.h"

/**
 * @file JointDistribution.h
 * @brief Joint probability distribution built from marginals and a copula.
 *
 * This header defines @ref JointDistribution, which combines independent
 * marginal distribution objects with a copula object to represent a correlated
 * multivariate distribution.
 *
 * @see IMarginalDistribution
 * @see ICopula
 */

/**
 * @class JointDistribution
 * @brief Multivariate distribution represented through marginals and a copula.
 *
 * The class owns one marginal distribution per dimension and a copula defining
 * the dependence structure between dimensions. Samples are generated by drawing
 * correlated uniforms from the copula and mapping them through each marginal
 * inverse CDF. Density evaluation combines marginal log-densities and the
 * copula log-density.
 */
class JointDistribution {
public:
    /**
     * @brief Constructs a joint distribution from marginals and a copula.
     *
     * Ownership of all marginal distributions and the copula is transferred to
     * the constructed object.
     *
     * @param marginals Marginal distributions, one per random-vector component.
     * @param copula    Copula encoding the dependence structure.
     */
    JointDistribution(std::vector<std::unique_ptr<IMarginalDistribution>> marginals,
                          std::unique_ptr<ICopula> copula);
    
    /**
     * @brief Draws multiple samples from the joint distribution.
     *
     * @param n Number of samples to generate.
     * @return Matrix-like vector containing @p n samples, one sample per row.
     */
    std::vector<std::vector<double>> sample(std::size_t n) const;

    /**
     * @brief Draws a single sample from the joint distribution.
     *
     * @return Random vector sampled from the distribution.
     */
    std::vector<double> sample() const;

    /**
     * @brief Evaluates the joint log-density at a given point.
     *
     * The value is computed as the sum of marginal log-densities plus the
     * copula log-density evaluated at the marginal CDF values:
     * \f[
     *   \log f_X(x) = \sum_i \log f_i(x_i) + \log c(F_1(x_1), \ldots, F_d(x_d)).
     * \f]
     *
     * @param x Point at which the log-density is evaluated.
     * @return Joint log-density value.
     *
     * @throws std::invalid_argument if @p x does not match the distribution dimension.
     */
    double logpdf(std::vector<double> x) const;

    /**
     * @brief Computes the negative Hessian of the joint log-density.
     *
     * The returned matrix corresponds to the local curvature matrix
     * \f$-\nabla_x^2 \log f_X(x)\f$. Internally, marginal derivatives and
     * copula derivatives are combined through the copula transformation.
     *
     * @param x Point at which the curvature is evaluated.
     * @return Curvature matrix in the original variable space.
     *
     * @throws std::invalid_argument if @p x does not match the distribution dimension.
     * @throws std::runtime_error if a non-finite intermediate value is detected.
     */
    RealMatrix curvature(std::vector<double> x) const;

    /**
     * @brief Returns the dimension of the random vector.
     *
     * @return Number of marginal distributions.
     */
    std::size_t dim();

    /**
     * @brief Returns the standard deviations of all marginals.
     *
     * @return Vector containing one standard deviation per marginal distribution.
     */
    std::vector<double> get_stds();

private:
    std::vector<std::unique_ptr<IMarginalDistribution>> marginals_; ///< Owned marginal distributions.
    std::unique_ptr<ICopula> copula_;                               ///< Owned copula defining dependence.
};



#endif