#if !defined(HYPERISO_OBSERVABLES_H)
#define HYPERISO_OBSERVABLES_H

enum class Observables {
    BR_BS_MUMU,
    BR_BS_MUMU_UNTAG,
    BR_BD_MUMU,
    // BR_BU_TAUNU,
    // BR_BU_TAUNU_NP_ONLY,
    ISOSPIN_ASYMMETRY_B_KSTAR_GAMMA,
};

#endif // HYPERISO_OBSERVABLES_H
