#ifndef TEMPLATE_MANAGER_H
#define TEMPLATE_MANAGER_H

#include <string>
#include <fstream>
#include <memory>

#include "ModelModifier.h"
#include "GeneralNumModelModifier.h"

/**
 * @file TemplateManager.h
 * @brief Declares managers for generating (numeric and non-numeric) model templates.
 *
 * Template managers own a ::ModelModifier or ::GeneralNumModelModifier and
 * drive the process of copying template files, instrumenting them and
 * writing parameter files.
 */

/**
 * @class TemplateManagerBase
 * @ingroup CodeGenerationModule
 * @brief Base class for managing template generation.
 *
 * Provides common facilities for:
 *  - holding model / Wilson identifiers,
 *  - storing a ::ModelModifier and ::GeneralNumModelModifier,
 *  - checking if a file has already been generated (using the `//42` marker),
 *  - exposing the set of interpreted dependencies (parameters).
 */
class TemplateManagerBase {
public:
    /**
     * @brief Constructs a manager with a given templates directory.
     * @param templatesDir Path to the directory containing template sources.
     */
    TemplateManagerBase(const std::string& templatesDir) : templatesDir(templatesDir) {}

    virtual ~TemplateManagerBase() = default;

    /**
     * @brief Public entry point for template generation.
     *
     * Delegates to the virtual ::generateTemplateImpl method implemented
     * by derived classes.
     *
     * @param templateName Name of the template (without extension).
     * @param outputPath   File path where the generated C++ file should be written.
     */
    void generateTemplate(const std::string& templateName, const std::string& outputPath) {
        generateTemplateImpl(templateName, outputPath);
    }

    /**
     * @brief Injects a custom model modifier.
     * @param modifier Unique pointer owning the ::ModelModifier instance.
     */
    void setModelModifier(std::unique_ptr<ModelModifier> modifier) { modelModifier = std::move(modifier); }

    /**
     * @brief Injects a numeric model modifier.
     * @param modifier Unique pointer owning the ::GeneralNumModelModifier instance.
     */
    void setNumModelModifier(std::unique_ptr<GeneralNumModelModifier> modifier) { numModifier = std::move(modifier); }

    /**
     * @brief Sets both model and Wilson names used during generation.
     * @param model  Model name.
     * @param wilson Wilson basis name.
     */
    void setModelAndWilson(std::string model, std::string wilson) { this->model = model; this->wilson = wilson; }

    /**
     * @brief Returns the set of interpreted parameters used by the numeric modifier.
     *
     * The set is built from the values of
     * ::GeneralNumModelModifier::get_interpreted_param_map().
     *
     * @return Unordered set of ::InterpretedParam representing all
     *         dependencies of the numeric template.
     */
    std::unordered_set<InterpretedParam> get_dependencies();

protected:
    /// Directory containing the template sources.
    std::string templatesDir;
    /// Wilson basis name.
    std::string wilson;
    /// Model name.
    std::string model;

    /// Optional modifier for non-numeric templates.
    std::unique_ptr<ModelModifier> modelModifier;
    /// Optional modifier for numeric templates.
    std::unique_ptr<GeneralNumModelModifier> numModifier;

    /**
     * @brief Actual implementation for generating a specific template.
     *
     * Derived classes implement the logic that:
     *  - locates the template file,
     *  - creates directories,
     *  - copies or transforms the contents,
     *  - optionally writes parameter files.
     *
     * @param templateName Template identifier (without extension).
     * @param outputPath   Destination C++ file path.
     */
    virtual void generateTemplateImpl(const std::string& templateName, const std::string& outputPath) = 0;

    /**
     * @brief Checks whether a file was already generated by this system.
     *
     * The method scans the small generated-file header for the marker
     * string `"//42"`. If found, the file is considered already generated.
     * This covers both numeric files (marker on line one) and analytical
     * files (marker immediately after the preserved first template line).
     *
     * @param path Path to the file to test.
     * @return `true` if file exists and contains the marker, `false` otherwise.
     */
    bool already_generated(const std::string& path);
};


/**
 * @class NumericTemplateManager
 * @ingroup CodeGenerationModule
 * @brief Template manager for numeric examples.
 *
 * This manager relies on a ::GeneralNumModelModifier to:
 *  - copy and adapt numeric example templates,
 *  - generate a parameter file and CSV for Wilson coefficients,
 *  - ensure helper headers (e.g. `csv_helper.*`) are copied into place.
 */
class NumericTemplateManager : public TemplateManagerBase {
public:
    /**
     * @brief Constructs a numeric template manager.
     * @param templatesDir Directory that conceptually hosts templates (not
     *                     always used directly, as file paths are typically
     *                     obtained from ::FileNameManager).
     */
    NumericTemplateManager(const std::string& templatesDir) : TemplateManagerBase(templatesDir)  {}

private:
     /// @copydoc TemplateManagerBase::generateTemplateImpl()
    void generateTemplateImpl(const std::string& templateName, const std::string& outputPath) override;
};

/**
 * @class NonNumericTemplateManager
 * @ingroup CodeGenerationModule
 * @brief Template manager for non-numeric model templates.
 *
 * This manager:
 *  - reads a textual template (e.g. `<templatesDir>/<name>.cpp`),
 *  - uses a ::ModelModifier to adapt it to the target model/Wilson setup,
 *  - injects a `//42` marker to signal that the file was already processed.
 */
class NonNumericTemplateManager : public TemplateManagerBase {
public:
    /**
     * @brief Constructs a non-numeric template manager.
     * @param templatesDir Directory containing non-numeric templates.
     */
    NonNumericTemplateManager(const std::string& templatesDir) : TemplateManagerBase(templatesDir)  {}

private:
    /// @copydoc TemplateManagerBase::generateTemplateImpl()
    void generateTemplateImpl(const std::string& templateName, const std::string& outputPath) override;
};


#endif  // TEMPLATE_MANAGER_H
