name: Run common test

on:
  push:
    paths:
      - "Hyperiso/Hyperiso/core/Common/**"

jobs:
  test-common:
    runs-on: ubuntu-latest
    name: Run Common Tests 
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make build-essential libgsl-dev

      - name: Configure Cmake
        run: cmake -S Hyperiso/Hyperiso/core -B build -DENABLE_TESTS=ON

      - name: Build Project
        run: cmake --build build --target testCommon

      - name: Run Common Tests
        run: ctest --test-dir build -L common --output-on-failure