name: Run sm test

on:
  push:
    paths:
      - "Hyperiso/Hyperiso/core/PhysicalModel/**"

jobs:

  test-PhysicalModelSM:
    runs-on: ubuntu-latest
    name: Run PhysicalModel(SM) Tests 
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make build-essential libgsl-dev
          
      - name: Configure Cmake
        run: cmake -S Hyperiso/Hyperiso/core -B build -DENABLE_TESTS=ON

      - name: Build Project
        run: cmake --build build --target testSMWilson testSMCQPrimeWilson testBase1Wilson testBase2Wilson

      - name: Run Common Tests
        run: ctest --test-dir build -L wilson --output-on-failure