name: C++ Project CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install CMake, Make, and Build Essentials
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make build-essential

    - name: Configure CMake
      run: cmake . -DENABLE_TESTS=ON

    - name: Build
      run: cmake --build .

    - name: Test
      run: ctest --output-on-failure


    # - name: Test