name: C++ Project CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup CMake
      uses: actions/setup-cmake@v1
      with:
        cmake-version: '3.18.2'

    - name: Setup Environment
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Configure CMake
      run: cmake .

    - name: Build
      run: make

    - name: Test