name: Database Changes CI

on:
  push:
    paths:
      - 'DataBase/**'
  pull_request:
    paths:
      - 'DataBase/**'

jobs:
  test-database:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make build-essential libgsl-dev

    - name: Configure CMake (Tests)
      run: cmake -S. -B build -DENABLE_TESTS=ON 

    - name: Build testReader
      run: cmake --build build

    - name: Run dbtest
      run: ctest --test-dir build -L database --output-on-failure
