name: Database Changes CI

on:
  push:
    paths:
      - 'DataBase/**'
  pull_request:
    paths:
      - 'DataBase/**'

jobs:
  test-database:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make build-essential

    - name: Configure CMake (Tests)
      run: cmake -S tests -B build

    - name: Build testReader
      run: cmake --build build/ --target testReader

    - name: Run testReader
      run: ./build/testReader
